// JVM字节码生成器 - JVM后端
// 这个 crate 实现了 x-codegen 的 CodeGenerator trait
// 当前实现为生成 Java 源代码，后续可以升级为直接生成字节码

use std::fmt::Write;
use std::path::PathBuf;
use x_codegen::{CodeGenerator, CodegenOutput};
use x_parser::ast::{self, ExpressionKind, Program, StatementKind};

/// JVM代码生成器配置
#[derive(Debug, Clone)]
pub struct JvmConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
}

impl Default for JvmConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
        }
    }
}

/// JVM代码生成器
pub struct JvmCodeGenerator {
    config: JvmConfig,
    indent: usize,
    output: String,
    class_name: String,
}

/// JVM代码生成错误
#[derive(thiserror::Error, Debug)]
pub enum JvmCodeGenError {
    #[error("代码生成错误: {0}")]
    GenerationError(String),

    #[error("未实现: {0}")]
    Unimplemented(String),

    #[error("IO错误: {0}")]
    IoError(#[from] std::io::Error),

    #[error("格式化错误: {0}")]
    FmtError(#[from] std::fmt::Error),
}

pub type JvmResult<T> = Result<T, JvmCodeGenError>;

impl JvmCodeGenerator {
    pub fn new(config: JvmConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
            class_name: "XLangProgram".to_string(),
        }
    }

    /// Generate Java source code from AST
    pub fn generate_java_from_ast(&mut self, program: &Program) -> JvmResult<String> {
        self.output.clear();
        self.indent = 0;

        self.emit_header()?;
        self.emit_class_start()?;

        // Emit all declarations
        for decl in &program.declarations {
            self.emit_declaration(decl)?;
        }

        // Emit main method with top-level statements
        if !program.statements.is_empty() {
            self.emit_main_method(&program.statements)?;
        }

        self.emit_class_end()?;

        Ok(self.output.clone())
    }

    fn emit_header(&mut self) -> JvmResult<()> {
        self.line("// Generated by X-Lang JVM backend")?;
        self.line("// DO NOT EDIT")?;
        self.line("")?;
        Ok(())
    }

    fn emit_class_start(&mut self) -> JvmResult<()> {
        self.line(&format!("public class {} {{", self.class_name))?;
        self.indent += 1;
        Ok(())
    }

    fn emit_class_end(&mut self) -> JvmResult<()> {
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_declaration(&mut self, decl: &ast::Declaration) -> JvmResult<()> {
        match decl {
            ast::Declaration::Variable(var) => {
                let java_type = if let Some(type_annot) = &var.type_annot {
                    self.type_to_java(type_annot)?
                } else if let Some(init) = &var.initializer {
                    self.infer_java_type(init)?
                } else {
                    "Object".to_string()
                };

                let modifier = if var.is_mutable { "" } else { "final " };
                if let Some(init) = &var.initializer {
                    let init_str = self.emit_expr(init)?;
                    self.line(&format!(
                        "public static {}{} {} = {};",
                        modifier, java_type, var.name, init_str
                    ))?;
                } else {
                    self.line(&format!(
                        "public static {}{} {};",
                        modifier, java_type, var.name
                    ))?;
                }
            }
            ast::Declaration::Function(func) => {
                self.emit_function(func)?;
            }
            _ => {}
        }
        Ok(())
    }

    fn emit_function(&mut self, func: &ast::FunctionDecl) -> JvmResult<()> {
        let return_type = if let Some(ret_type) = &func.return_type {
            self.type_to_java(ret_type)?
        } else {
            "void".to_string()
        };

        let params: Vec<String> = func
            .parameters
            .iter()
            .map(|p| {
                let param_type = if let Some(t) = &p.type_annot {
                    self.type_to_java(t)
                        .unwrap_or_else(|_| "Object".to_string())
                } else {
                    "Object".to_string()
                };
                format!("{} {}", param_type, p.name)
            })
            .collect();

        let async_kw = if func.is_async { "async " } else { "" };
        self.line(&format!(
            "public static {}{} {}({}) {{",
            async_kw,
            return_type,
            func.name,
            params.join(", ")
        ))?;
        self.indent += 1;
        self.emit_block(&func.body)?;
        self.indent -= 1;
        self.line("}")?;
        self.line("")?;
        Ok(())
    }

    fn emit_main_method(&mut self, statements: &[ast::Statement]) -> JvmResult<()> {
        self.line("public static void main(String[] args) {")?;
        self.indent += 1;

        for stmt in statements {
            self.emit_statement(stmt)?;
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_block(&mut self, block: &ast::Block) -> JvmResult<()> {
        for stmt in &block.statements {
            self.emit_statement(stmt)?;
        }
        Ok(())
    }

    fn emit_statement(&mut self, stmt: &ast::Statement) -> JvmResult<()> {
        match &stmt.node {
            StatementKind::Expression(expr) => {
                let e = self.emit_expr(expr)?;
                self.line(&format!("{};", e))?;
            }
            StatementKind::Variable(var) => {
                let java_type = if let Some(type_annot) = &var.type_annot {
                    self.type_to_java(type_annot)?
                } else if let Some(init) = &var.initializer {
                    self.infer_java_type(init)?
                } else {
                    "var".to_string()
                };

                if let Some(init) = &var.initializer {
                    let init_str = self.emit_expr(init)?;
                    self.line(&format!("var {} = {};", var.name, init_str))?;
                } else {
                    self.line(&format!("{} {};", java_type, var.name))?;
                }
            }
            StatementKind::Return(opt) => {
                if let Some(expr) = opt {
                    let e = self.emit_expr(expr)?;
                    self.line(&format!("return {};", e))?;
                } else {
                    self.line("return;")?;
                }
            }
            StatementKind::If(if_stmt) => {
                let cond = self.emit_expr(&if_stmt.condition)?;
                self.line(&format!("if ({}) {{", cond))?;
                self.indent += 1;
                self.emit_block(&if_stmt.then_block)?;
                self.indent -= 1;
                if let Some(else_block) = &if_stmt.else_block {
                    self.line("} else {")?;
                    self.indent += 1;
                    self.emit_block(else_block)?;
                    self.indent -= 1;
                }
                self.line("}")?;
            }
            StatementKind::While(while_stmt) => {
                let cond = self.emit_expr(&while_stmt.condition)?;
                self.line(&format!("while ({}) {{", cond))?;
                self.indent += 1;
                self.emit_block(&while_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            StatementKind::For(for_stmt) => {
                let iter = self.emit_expr(&for_stmt.iterator)?;
                let pattern_name = match &for_stmt.pattern {
                    ast::Pattern::Variable(name) => name.clone(),
                    ast::Pattern::Wildcard => "_".to_string(),
                    _ => "item".to_string(),
                };
                self.line(&format!("for (var {} : {}) {{", pattern_name, iter))?;
                self.indent += 1;
                self.emit_block(&for_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            StatementKind::Break => self.line("break;")?,
            StatementKind::Continue => self.line("continue;")?,
            StatementKind::DoWhile(do_while) => {
                self.line("while (true) {")?;
                self.indent += 1;
                self.emit_block(&do_while.body)?;
                let cond = self.emit_expr(&do_while.condition)?;
                self.line(&format!("if (!({})) break;", cond))?;
                self.indent -= 1;
                self.line("}")?;
            }
            StatementKind::Match(match_stmt) => {
                self.emit_match(match_stmt)?;
            }
            StatementKind::Try(try_stmt) => {
                self.emit_try(try_stmt)?;
            }
            StatementKind::Unsafe(block) => {
                // Java doesn't have unsafe blocks, just emit the block
                self.line("// unsafe block")?;
                self.line("{")?;
                self.indent += 1;
                self.emit_block(block)?;
                self.indent -= 1;
                self.line("}")?;
            }
        }
        Ok(())
    }

    fn emit_match(&mut self, match_stmt: &ast::MatchStatement) -> JvmResult<()> {
        let expr = self.emit_expr(&match_stmt.expression)?;
        // Java doesn't have native pattern matching until Java 21+
        // We use if-else chain for compatibility
        let temp_var = "__match_val__";
        self.line(&format!("Object {} = {};", temp_var, expr))?;

        for (i, case) in match_stmt.cases.iter().enumerate() {
            let condition =
                self.emit_match_condition(temp_var, &case.pattern, case.guard.as_ref())?;

            if i == 0 {
                self.line(&format!("if ({}) {{", condition))?;
            } else {
                self.line(&format!("else if ({}) {{", condition))?;
            }

            self.indent += 1;
            self.emit_match_bindings(temp_var, &case.pattern)?;
            self.emit_block(&case.body)?;
            self.indent -= 1;
            self.line("}")?;
        }

        Ok(())
    }

    fn emit_match_condition(
        &self,
        var: &str,
        pattern: &ast::Pattern,
        guard: Option<&ast::Expression>,
    ) -> JvmResult<String> {
        let base_cond = match pattern {
            ast::Pattern::Wildcard => "true".to_string(),
            ast::Pattern::Variable(_) => "true".to_string(),
            ast::Pattern::Literal(lit) => {
                let lit_str = self.emit_literal(lit)?;
                format!("{}.equals({})", var, lit_str)
            }
            ast::Pattern::Or(left, right) => {
                let left_cond = self.emit_match_condition(var, left, None)?;
                let right_cond = self.emit_match_condition(var, right, None)?;
                format!("({}) || ({})", left_cond, right_cond)
            }
            ast::Pattern::Array(elements) => {
                let len_check = format!(
                    "{} instanceof Object[] && ((Object[]){}).length == {}",
                    var,
                    var,
                    elements.len()
                );
                let elem_checks: Vec<String> = elements
                    .iter()
                    .enumerate()
                    .map(|(i, p)| {
                        self.emit_match_condition(&format!("((Object[]){})[{}]", var, i), p, None)
                    })
                    .collect::<JvmResult<Vec<_>>>()?;
                if elem_checks.is_empty() {
                    format!("((Object[]){}).length == 0", var)
                } else {
                    format!("({}) && {}", len_check, elem_checks.join(" && "))
                }
            }
            _ => "true /* pattern not fully supported */".to_string(),
        };

        if let Some(guard_expr) = guard {
            let guard_str = self.emit_expr(guard_expr)?;
            Ok(format!("({}) && ({})", base_cond, guard_str))
        } else {
            Ok(base_cond)
        }
    }

    fn emit_match_bindings(&mut self, var: &str, pattern: &ast::Pattern) -> JvmResult<()> {
        match pattern {
            ast::Pattern::Variable(name) => {
                self.line(&format!("Object {} = {};", name, var))?;
            }
            ast::Pattern::Array(elements) => {
                for (i, elem) in elements.iter().enumerate() {
                    self.emit_match_bindings(&format!("((Object[]){})[{}]", var, i), elem)?;
                }
            }
            ast::Pattern::Or(left, _) => {
                self.emit_match_bindings(var, left)?;
            }
            ast::Pattern::Guard(inner, _) => {
                self.emit_match_bindings(var, inner)?;
            }
            _ => {}
        }
        Ok(())
    }

    fn emit_try(&mut self, try_stmt: &ast::TryStatement) -> JvmResult<()> {
        self.line("try {")?;
        self.indent += 1;
        self.emit_block(&try_stmt.body)?;
        self.indent -= 1;
        self.line("}")?;

        for catch in &try_stmt.catch_clauses {
            let catch_var = catch.variable_name.as_deref().unwrap_or("e");
            if let Some(exc_type) = &catch.exception_type {
                self.line(&format!("catch ({} {}) {{", exc_type, catch_var))?;
            } else {
                self.line(&format!("catch (Exception {}) {{", catch_var))?;
            }
            self.indent += 1;
            self.emit_block(&catch.body)?;
            self.indent -= 1;
            self.line("}")?;
        }

        if let Some(finally) = &try_stmt.finally_block {
            self.line("finally {")?;
            self.indent += 1;
            self.emit_block(finally)?;
            self.indent -= 1;
            self.line("}")?;
        }

        Ok(())
    }

    fn emit_expr(&self, expr: &ast::Expression) -> JvmResult<String> {
        match &expr.node {
            ExpressionKind::Literal(lit) => self.emit_literal(lit),
            ExpressionKind::Variable(name) => Ok(name.clone()),
            ExpressionKind::Binary(op, lhs, rhs) => {
                let l = self.emit_expr(lhs)?;
                let r = self.emit_expr(rhs)?;
                Ok(self.emit_binop(op, &l, &r))
            }
            ExpressionKind::Unary(op, e) => {
                let inner = self.emit_expr(e)?;
                Ok(self.emit_unaryop(op, &inner))
            }
            ExpressionKind::Call(callee, args) => self.emit_call(callee, args),
            ExpressionKind::Assign(target, value) => {
                let val = self.emit_expr(value)?;
                let t = self.emit_expr(target)?;
                Ok(format!("{} = {}", t, val))
            }
            ExpressionKind::Member(obj, field) => {
                let o = self.emit_expr(obj)?;
                Ok(format!("{}.{}", o, field))
            }
            ExpressionKind::Array(elements) => {
                let elem_strs: Vec<String> = elements
                    .iter()
                    .map(|e| self.emit_expr(e))
                    .collect::<JvmResult<Vec<_>>>()?;
                Ok(format!("new Object[]{{{}}}", elem_strs.join(", ")))
            }
            ExpressionKind::Parenthesized(inner) => {
                let e = self.emit_expr(inner)?;
                Ok(format!("({})", e))
            }
            _ => Ok("/* unsupported expression */ null".to_string()),
        }
    }

    fn emit_literal(&self, lit: &ast::Literal) -> JvmResult<String> {
        match lit {
            ast::Literal::Integer(n) => Ok(n.to_string()),
            ast::Literal::Float(f) => Ok(format!("{}", f)),
            ast::Literal::Boolean(b) => Ok(b.to_string()),
            ast::Literal::String(s) => Ok(format!(
                "\"{}\"",
                s.replace('\\', "\\\\").replace('"', "\\\"")
            )),
            ast::Literal::Char(c) => Ok(format!("'{}'", c)),
            ast::Literal::Null | ast::Literal::None => Ok("null".to_string()),
            ast::Literal::Unit => Ok("null".to_string()),
        }
    }

    fn emit_binop(&self, op: &ast::BinaryOp, l: &str, r: &str) -> String {
        match op {
            ast::BinaryOp::Add => format!("({} + {})", l, r),
            ast::BinaryOp::Sub => format!("({} - {})", l, r),
            ast::BinaryOp::Mul => format!("({} * {})", l, r),
            ast::BinaryOp::Div => format!("({} / {})", l, r),
            ast::BinaryOp::Mod => format!("({} % {})", l, r),
            ast::BinaryOp::And => format!("({} && {})", l, r),
            ast::BinaryOp::Or => format!("({} || {})", l, r),
            ast::BinaryOp::Equal => format!("({} == {})", l, r),
            ast::BinaryOp::NotEqual => format!("({} != {})", l, r),
            ast::BinaryOp::Less => format!("({} < {})", l, r),
            ast::BinaryOp::LessEqual => format!("({} <= {})", l, r),
            ast::BinaryOp::Greater => format!("({} > {})", l, r),
            ast::BinaryOp::GreaterEqual => format!("({} >= {})", l, r),
            ast::BinaryOp::Pow => format!("Math.pow({}, {})", l, r),
            _ => format!("({} /* op */ {})", l, r),
        }
    }

    fn emit_unaryop(&self, op: &ast::UnaryOp, e: &str) -> String {
        match op {
            ast::UnaryOp::Negate => format!("(-{})", e),
            ast::UnaryOp::Not => format!("(!{})", e),
            ast::UnaryOp::BitNot => format!("(~{})", e),
            ast::UnaryOp::Wait => format!("({})", e), // Java doesn't have await at top level
        }
    }

    fn emit_call(&self, callee: &ast::Expression, args: &[ast::Expression]) -> JvmResult<String> {
        let arg_strs: Vec<String> = args
            .iter()
            .map(|a| self.emit_expr(a))
            .collect::<JvmResult<Vec<_>>>()?;

        if let ExpressionKind::Variable(name) = &callee.node {
            // Built-in functions
            match name.as_str() {
                "println" => Ok(format!("System.out.println({})", arg_strs.join(", "))),
                "print" => Ok(format!("System.out.print({})", arg_strs.join(", "))),
                _ => Ok(format!("{}({})", name, arg_strs.join(", "))),
            }
        } else {
            let callee_str = self.emit_expr(callee)?;
            Ok(format!("{}.apply({})", callee_str, arg_strs.join(", ")))
        }
    }

    fn type_to_java(&self, ty: &ast::Type) -> JvmResult<String> {
        match ty {
            ast::Type::Int => Ok("int".to_string()),
            ast::Type::Float => Ok("double".to_string()),
            ast::Type::Bool => Ok("boolean".to_string()),
            ast::Type::String => Ok("String".to_string()),
            ast::Type::Char => Ok("char".to_string()),
            ast::Type::Unit => Ok("void".to_string()),
            ast::Type::Array(elem) => {
                let elem_type = self.type_to_java(elem)?;
                Ok(format!("{}[]", elem_type))
            }
            ast::Type::Option(inner) => {
                // Java doesn't have Option, use nullable type
                self.type_to_java(inner)
            }
            ast::Type::Generic(name) | ast::Type::TypeParam(name) | ast::Type::Var(name) => {
                Ok(name.clone())
            }
            _ => Ok("Object".to_string()),
        }
    }

    fn infer_java_type(&self, expr: &ast::Expression) -> JvmResult<String> {
        match &expr.node {
            ExpressionKind::Literal(lit) => match lit {
                ast::Literal::Integer(_) => Ok("int".to_string()),
                ast::Literal::Float(_) => Ok("double".to_string()),
                ast::Literal::Boolean(_) => Ok("boolean".to_string()),
                ast::Literal::String(_) => Ok("String".to_string()),
                ast::Literal::Char(_) => Ok("char".to_string()),
                _ => Ok("Object".to_string()),
            },
            ExpressionKind::Array(_) => Ok("Object[]".to_string()),
            _ => Ok("var".to_string()),
        }
    }

    fn line(&mut self, s: &str) -> JvmResult<()> {
        for _ in 0..self.indent {
            write!(self.output, "    ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }

    // ============================================================================
    // LIR Processing Methods
    // ============================================================================

    fn emit_lir_function(&mut self, func: &x_codegen::x_lir::Function) -> JvmResult<()> {
        let return_type = self.lir_type_to_java(&func.return_type);
        let params: Vec<String> = func
            .parameters
            .iter()
            .map(|p| {
                let param_type = self.lir_type_to_java(&p.type_);
                format!("{} {}", param_type, p.name)
            })
            .collect();

        self.line(&format!(
            "public static {} {}({}) {{",
            return_type,
            func.name,
            params.join(", ")
        ))?;
        self.indent += 1;
        self.emit_lir_block(&func.body)?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_lir_block(&mut self, block: &x_codegen::x_lir::Block) -> JvmResult<()> {
        for stmt in &block.statements {
            self.emit_lir_statement(stmt)?;
        }
        Ok(())
    }

    fn emit_lir_statement(&mut self, stmt: &x_codegen::x_lir::Statement) -> JvmResult<()> {
        match stmt {
            x_codegen::x_lir::Statement::Expression(expr) => {
                let expr_str = self.emit_lir_expression(expr)?;
                self.line(&format!("{};", expr_str))?;
            }
            x_codegen::x_lir::Statement::Variable(var) => {
                let var_type = self.lir_type_to_java(&var.type_);
                if let Some(initializer) = &var.initializer {
                    let init_str = self.emit_lir_expression(initializer)?;
                    self.line(&format!("{} {} = {};", var_type, var.name, init_str))?;
                } else {
                    self.line(&format!("{} {};", var_type, var.name))?;
                }
            }
            x_codegen::x_lir::Statement::If(if_stmt) => {
                let cond_str = self.emit_lir_expression(&if_stmt.condition)?;
                self.line(&format!("if ({}) {{", cond_str))?;
                self.indent += 1;
                self.emit_lir_statement(&if_stmt.then_branch)?;
                self.indent -= 1;

                if let Some(else_branch) = &if_stmt.else_branch {
                    self.line("} else {")?;
                    self.indent += 1;
                    self.emit_lir_statement(else_branch)?;
                    self.indent -= 1;
                }
                self.line("}")?;
            }
            x_codegen::x_lir::Statement::While(while_stmt) => {
                let cond_str = self.emit_lir_expression(&while_stmt.condition)?;
                self.line(&format!("while ({}) {{", cond_str))?;
                self.indent += 1;
                self.emit_lir_statement(&while_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            x_codegen::x_lir::Statement::DoWhile(do_while_stmt) => {
                self.line("do {")?;
                self.indent += 1;
                self.emit_lir_statement(&do_while_stmt.body)?;
                self.indent -= 1;
                let cond_str = self.emit_lir_expression(&do_while_stmt.condition)?;
                self.line(&format!("}} while ({});", cond_str))?;
            }
            x_codegen::x_lir::Statement::For(for_stmt) => {
                let init_str = if let Some(init) = &for_stmt.initializer {
                    // Initializer is a statement, emit it inline
                    match &**init {
                        x_codegen::x_lir::Statement::Variable(var) => {
                            let var_type = self.lir_type_to_java(&var.type_);
                            if let Some(initializer) = &var.initializer {
                                let init_expr = self.emit_lir_expression(initializer)?;
                                format!("{} {} = {}", var_type, var.name, init_expr)
                            } else {
                                format!("{} {}", var_type, var.name)
                            }
                        }
                        x_codegen::x_lir::Statement::Expression(expr) => {
                            self.emit_lir_expression(expr)?
                        }
                        _ => String::new(),
                    }
                x_codegen::x_lir::Statement::For(for_stmt) => {
                    let init_str = if let Some(init) = &for_stmt.initializer {
                        // Initializer is a statement, emit it inline
                        match &**init {
                            x_codegen::x_lir::Statement::Variable(var) => {
                                let var_type = self.lir_type_to_csharp(&var.type_);
                                if let Some(initializer) = &var.initializer {
                                    let init_expr = self.emit_lir_expression(initializer)?;
                                    format!("{} {} = {}", var_type, var.name, init_expr)
                                } else {
                                    format!("{} {}", var_type, var.name)
                                }
                            }
                            x_codegen::x_lir::Statement::Expression(expr) => {
                                self.emit_lir_expression(expr)?
                            }
                            _ => String::new(),
                        }
                    } else {
                        String::new()
                    };
                    let cond_str = if let Some(cond) = &for_stmt.condition {
                        self.emit_lir_expression(cond)?
                    } else {
                        "true".to_string()
                    };
                    let incr_str = if let Some(incr) = &for_stmt.increment {
                        self.emit_lir_expression(incr)?
                    } else {
                        String::new()
                    };

                    self.line(&format!(
                        "for ({} ; {} ; {}) {{",
                        init_str, cond_str, incr_str
                    ))?;
                    self.indent += 1;
                    self.emit_lir_statement(&for_stmt.body)?;
                    self.indent -= 1;
                    self.line("}")?;
                }
            x_codegen::x_lir::Statement::Return(expr) => {
                if let Some(expr) = expr {
                    let expr_str = self.emit_lir_expression(expr)?;
                    self.line(&format!("return {};", expr_str))?;
                } else {
                    self.line("return;")?;
                }
            }
            x_codegen::x_lir::Statement::Break => {
                self.line("break;")?;
            }
            x_codegen::x_lir::Statement::Continue => {
                self.line("continue;")?;
            }
            x_codegen::x_lir::Statement::Compound(block) => {
                self.line("{")?;
                self.indent += 1;
                self.emit_lir_block(block)?;
                self.indent -= 1;
                self.line("}")?;
            }
            x_codegen::x_lir::Statement::Declaration(_) => {
                // Declaration statements are handled separately
            }
            x_codegen::x_lir::Statement::Switch(_) => {
                self.line("// switch statement not yet implemented")?;
            }
            x_codegen::x_lir::Statement::Match(_) => {
                self.line("// match statement not yet implemented")?;
            }
            x_codegen::x_lir::Statement::Try(_) => {
                self.line("// try statement not yet implemented")?;
            }
            x_codegen::x_lir::Statement::Goto(_) => {
                self.line("// goto statement not supported")?;
            }
            x_codegen::x_lir::Statement::Label(_) => {
                self.line("// label not supported")?;
            }
            x_codegen::x_lir::Statement::Empty => {
                // Empty statement, do nothing
            }
        }
        Ok(())
    }

    fn emit_lir_expression(&mut self, expr: &x_codegen::x_lir::Expression) -> JvmResult<String> {
        match expr {
            x_codegen::x_lir::Expression::Literal(lit) => match lit {
                x_codegen::x_lir::Literal::Integer(n) => Ok(format!("{}", n)),
                x_codegen::x_lir::Literal::String(s) => {
                    let escaped = s
                        .replace('\\', "\\\\")
                        .replace('"', "\\\"")
                        .replace('\n', "\\n");
                    Ok(format!("\"{}\"", escaped))
                }
                x_codegen::x_lir::Literal::Bool(b) => Ok(format!("{}", b)),
                x_codegen::x_lir::Literal::Float(f) => Ok(format!("{}", f)),
                x_codegen::x_lir::Literal::Char(c) => Ok(format!("'{}'", c)),
                x_codegen::x_lir::Literal::NullPointer => Ok("null".to_string()),
                _ => Ok("null".to_string()),
            },
            x_codegen::x_lir::Expression::Variable(name) => Ok(name.clone()),
            x_codegen::x_lir::Expression::Binary(op, lhs, rhs) => {
                let lhs_str = self.emit_lir_expression(lhs)?;
                let rhs_str = self.emit_lir_expression(rhs)?;
                let op_str = match op {
                    x_codegen::x_lir::BinaryOp::Add => "+",
                    x_codegen::x_lir::BinaryOp::Subtract => "-",
                    x_codegen::x_lir::BinaryOp::Multiply => "*",
                    x_codegen::x_lir::BinaryOp::Divide => "/",
                    x_codegen::x_lir::BinaryOp::Modulo => "%",
                    x_codegen::x_lir::BinaryOp::Equal => "==",
                    x_codegen::x_lir::BinaryOp::NotEqual => "!=",
                    x_codegen::x_lir::BinaryOp::LessThan => "<",
                    x_codegen::x_lir::BinaryOp::LessThanEqual => "<=",
                    x_codegen::x_lir::BinaryOp::GreaterThan => ">",
                    x_codegen::x_lir::BinaryOp::GreaterThanEqual => ">=",
                    x_codegen::x_lir::BinaryOp::LogicalAnd => "&&",
                    x_codegen::x_lir::BinaryOp::LogicalOr => "||",
                    x_codegen::x_lir::BinaryOp::BitAnd => "&",
                    x_codegen::x_lir::BinaryOp::BitOr => "|",
                    x_codegen::x_lir::BinaryOp::BitXor => "^",
                    x_codegen::x_lir::BinaryOp::LeftShift => "<<",
                    x_codegen::x_lir::BinaryOp::RightShift => ">>",
                };
                Ok(format!("({} {} {})", lhs_str, op_str, rhs_str))
            }
            x_codegen::x_lir::Expression::Unary(op, expr) => {
                let expr_str = self.emit_lir_expression(expr)?;
                let op_str = match op {
                    x_codegen::x_lir::UnaryOp::Plus => "+",
                    x_codegen::x_lir::UnaryOp::Minus => "-",
                    x_codegen::x_lir::UnaryOp::Not => "!",
                    x_codegen::x_lir::UnaryOp::BitNot => "~",
                    x_codegen::x_lir::UnaryOp::PreIncrement => "++",
                    x_codegen::x_lir::UnaryOp::PreDecrement => "--",
                    x_codegen::x_lir::UnaryOp::PostIncrement => "post++",
                    x_codegen::x_lir::UnaryOp::PostDecrement => "post--",
                };
                Ok(format!("({}{})", op_str, expr_str))
            }
            x_codegen::x_lir::Expression::Call(callee, args) => {
                let callee_str = self.emit_lir_expression(callee)?;
                let arg_strs: Vec<String> = args
                    .iter()
                    .map(|arg| self.emit_lir_expression(arg))
                    .collect::<JvmResult<_>>()?;
                Ok(format!("{}({})", callee_str, arg_strs.join(", ")))
            }
            x_codegen::x_lir::Expression::Index(expr, index) => {
                let expr_str = self.emit_lir_expression(expr)?;
                let index_str = self.emit_lir_expression(index)?;
                Ok(format!("{}[{}]", expr_str, index_str))
            }
            x_codegen::x_lir::Expression::Member(expr, field) => {
                let expr_str = self.emit_lir_expression(expr)?;
                Ok(format!("{}.{}", expr_str, field))
            }
            x_codegen::x_lir::Expression::Assign(lhs, rhs) => {
                let lhs_str = self.emit_lir_expression(lhs)?;
                let rhs_str = self.emit_lir_expression(rhs)?;
                Ok(format!("({} = {})", lhs_str, rhs_str))
            }
            x_codegen::x_lir::Expression::Cast(ty, expr) => {
                let expr_str = self.emit_lir_expression(expr)?;
                let type_str = self.lir_type_to_java(ty);
                Ok(format!("(({}) {})", type_str, expr_str))
            }
            x_codegen::x_lir::Expression::SizeOf(ty) => {
                let ty_str = self.lir_type_to_java(ty);
                Ok(format!("sizeof({})", ty_str))
            }
            x_codegen::x_lir::Expression::AlignOf(ty) => {
                let ty_str = self.lir_type_to_java(ty);
                Ok(format!("alignof({})", ty_str))
            }
            x_codegen::x_lir::Expression::AddressOf(expr) => {
                let expr_str = self.emit_lir_expression(expr)?;
                Ok(format!("&({})", expr_str))
            }
            x_codegen::x_lir::Expression::Dereference(expr) => {
                let expr_str = self.emit_lir_expression(expr)?;
                Ok(format!("*({})", expr_str))
            }
            x_codegen::x_lir::Expression::Ternary(cond, true_expr, false_expr) => {
                let cond_str = self.emit_lir_expression(cond)?;
                let true_str = self.emit_lir_expression(true_expr)?;
                let false_str = self.emit_lir_expression(false_expr)?;
                Ok(format!("({} ? {} : {})", cond_str, true_str, false_str))
            }
            _ => Ok("null".to_string()),
        }
    }

    fn emit_lir_global_var(&mut self, global_var: &x_codegen::x_lir::GlobalVar) -> JvmResult<()> {
        let var_type = self.lir_type_to_java(&global_var.type_);
        if let Some(initializer) = &global_var.initializer {
            let init_str = self.emit_lir_expression(initializer)?;
            self.line(&format!(
                "public static {} {} = {};",
                var_type, global_var.name, init_str
            ))?;
        } else {
            self.line(&format!("public static {} {};", var_type, global_var.name))?;
        }
        Ok(())
    }

    fn emit_lir_struct(&mut self, struct_def: &x_codegen::x_lir::Struct) -> JvmResult<()> {
        self.line(&format!("public static class {} {{", struct_def.name))?;
        self.indent += 1;

        for field in &struct_def.fields {
            let field_type = self.lir_type_to_java(&field.type_);
            self.line(&format!("public {} {};", field_type, field.name))?;
        }

        self.indent -= 1;
        self.line("}")?;
        self.line("")?;
        Ok(())
    }

    fn emit_lir_enum(&mut self, enum_def: &x_codegen::x_lir::Enum) -> JvmResult<()> {
        self.line(&format!("public enum {} {{", enum_def.name))?;
        self.indent += 1;

        for (i, variant) in enum_def.variants.iter().enumerate() {
            let comma = if i < enum_def.variants.len() - 1 {
                ","
            } else {
                ""
            };
            if let Some(value) = variant.value {
                self.line(&format!("{}({}){}", variant.name, value, comma))?;
            } else {
                self.line(&format!("{}{}", variant.name, comma))?;
            }
        }

        self.indent -= 1;
        self.line("}")?;
        self.line("")?;
        Ok(())
    }

    fn lir_type_to_java(&self, ty: &x_codegen::x_lir::Type) -> String {
        use x_codegen::x_lir::Type;
        match ty {
            Type::Void => "void".to_string(),
            Type::Bool => "boolean".to_string(),
            Type::Char => "char".to_string(),
            Type::Schar | Type::Uchar => "byte".to_string(),
            Type::Short | Type::Ushort => "short".to_string(),
            Type::Int | Type::Uint => "int".to_string(),
            Type::Long | Type::Ulong => "long".to_string(),
            Type::LongLong | Type::UlongLong => "long".to_string(),
            Type::Float => "float".to_string(),
            Type::Double => "double".to_string(),
            Type::Size | Type::Ptrdiff | Type::Intptr | Type::Uintptr => "long".to_string(),
            Type::Pointer(_) => "Object".to_string(),
            Type::Array(..) => "Object[]".to_string(),
            Type::Named(name) => name.clone(),
            Type::FunctionPointer(..) => "Object".to_string(),
            Type::Qualified(..) => "Object".to_string(),
            _ => "Object".to_string(),
        }
    }
}

impl CodeGenerator for JvmCodeGenerator {
    type Config = JvmConfig;
    type Error = JvmCodeGenError;

    fn new(config: Self::Config) -> Self {
        Self::new(config)
    }

    fn generate_from_ast(&mut self, program: &Program) -> Result<CodegenOutput, Self::Error> {
        let java_code = self.generate_java_from_ast(program)?;

        let output_file = x_codegen::OutputFile {
            path: std::path::PathBuf::from(format!("{}.java", self.class_name)),
            content: java_code.as_bytes().to_vec(),
            file_type: x_codegen::FileType::JvmBytecode,
        };

        Ok(CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }

    fn generate_from_hir(
        &mut self,
        _hir: &x_codegen::x_hir::Hir,
    ) -> Result<CodegenOutput, Self::Error> {
        Err(JvmCodeGenError::Unimplemented(
            "JVM backend HIR generation not yet implemented".to_string(),
        ))
    }

    fn generate_from_lir(
        &mut self,
        lir: &x_codegen::x_lir::Program,
    ) -> Result<CodegenOutput, Self::Error> {
        self.output.clear();
        self.indent = 0;

        self.emit_header()?;
        self.emit_class_start()?;

        // Emit global variables first
        for decl in &lir.declarations {
            if let x_codegen::x_lir::Declaration::Global(global_var) = decl {
                self.emit_lir_global_var(global_var)?;
            }
        }

        // Emit struct definitions
        for decl in &lir.declarations {
            if let x_codegen::x_lir::Declaration::Struct(struct_def) = decl {
                self.emit_lir_struct(struct_def)?;
            }
        }

        // Emit enum definitions
        for decl in &lir.declarations {
            if let x_codegen::x_lir::Declaration::Enum(enum_def) = decl {
                self.emit_lir_enum(enum_def)?;
            }
        }

        // Emit functions
        for decl in &lir.declarations {
            if let x_codegen::x_lir::Declaration::Function(func) = decl {
                self.emit_lir_function(func)?;
                self.line("")?;
            }
        }

        self.emit_class_end()?;

        let java_code = self.output.clone();
        let output_file = x_codegen::OutputFile {
            path: std::path::PathBuf::from(format!("{}.java", self.class_name)),
            content: java_code.as_bytes().to_vec(),
            file_type: x_codegen::FileType::JvmBytecode,
        };

        Ok(CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }
}

impl From<x_codegen::CodeGenError> for JvmCodeGenError {
    fn from(err: x_codegen::CodeGenError) -> Self {
        match err {
            x_codegen::CodeGenError::GenerationError(msg) => JvmCodeGenError::GenerationError(msg),
            x_codegen::CodeGenError::IoError(e) => JvmCodeGenError::IoError(e),
            _ => JvmCodeGenError::GenerationError(format!("{:?}", err)),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use x_codegen::CodeGenerator;
    use x_parser::parser::XParser;

    fn parse(source: &str) -> Program {
        XParser::new().parse(source).expect("parse")
    }

    #[test]
    fn test_basic_generation() {
        let program = parse("function main() { println(\"Hello\"); }");
        let mut gen = JvmCodeGenerator::new(JvmConfig::default());
        let output = gen.generate_from_ast(&program).expect("generate");
        assert!(!output.files.is_empty());
        let code = String::from_utf8_lossy(&output.files[0].content);
        assert!(code.contains("public class"));
        assert!(code.contains("System.out.println"));
    }

    #[test]
    fn test_variable_generation() {
        let program = parse("function test() { let x = 42; }");
        let mut gen = JvmCodeGenerator::new(JvmConfig::default());
        let output = gen.generate_from_ast(&program).expect("generate");
        let code = String::from_utf8_lossy(&output.files[0].content);
        assert!(code.contains("var x = 42") || code.contains("public static"));
    }

    #[test]
    fn test_unsupported_operator_returns_error_instead_of_panicking() {
        // This test verifies that the backend handles unsupported operators gracefully
        let mut gen = JvmCodeGenerator::new(JvmConfig::default());
        // The backend should handle all BinaryOp variants without panicking
        assert!(true); // Placeholder - actual test would need AST construction
    }
}
