// Generated by X-Lang C23 backend
// DO NOT EDIT

#include "x_runtime.h"

XValue x_test_basic(void);
XValue x_main(void);

XValue x_test_basic(void) {
    x_print(x_string("=== 测试基本功能 ==="));
    XValue hello = x_string("Hello, World!");
    x_print(hello);
    XValue number = x_int(42LL);
    x_print(x_add(x_string("Number: "), x_to_string(number)));
    XValue flag = x_bool(true);
    x_print(x_add(x_string("Flag: "), x_to_string(flag)));
    x_print(x_null());
    x_print(x_string("测试完成!"));
    return x_null();
}

XValue x_main(void) {
    x_test_basic();
    return x_null();
}

int main(int argc, char **argv) {
    x_main();
    return 0;
}
