// Generated by X-Lang C23 backend
// DO NOT EDIT

#include "x_runtime.h"

// 辅助函数实现
XValue x_arg_count(void) {
    return x_len(x_args());
}

XValue x_str_ends_with(XValue s, XValue suffix) {
    int64_t s_len = x_as_int(x_len(s));
    int64_t suffix_len = x_as_int(x_len(suffix));
    if (suffix_len == 0) {
        return x_bool(true);
    } else if (suffix_len > s_len) {
        return x_bool(false);
    } else {
        int64_t start = s_len - suffix_len;
        XValue s_sub = x_substring(s, x_int(start), x_len(s));
        return x_eq(s_sub, suffix);
    }
}

XValue x_path_join(XValue paths) {
    if (x_as_int(x_len(paths)) == 0) {
        return x_string("");
    } else if (x_as_int(x_len(paths)) == 1) {
        return x_index_get(paths, x_int(0LL));
    } else {
        XValue os = x_os_type();
        XValue sep = x_string("/");
        if (x_as_bool(x_eq(os, x_string("Windows")))) {
            sep = x_string("\\");
        }
        XValue result = x_index_get(paths, x_int(0LL));
        for (int64_t i = 1; i < x_as_int(x_len(paths)); i++) {
            XValue path = x_index_get(paths, x_int(i));
            if (x_as_bool(x_neq(result, x_string(""))) && !x_as_bool(x_str_ends_with(result, sep))) {
                result = x_add(result, sep);
            }
            if (x_as_bool(x_str_starts_with(path, sep))) {
                result = x_add(result, x_substring(path, x_int(1LL), x_len(path)));
            } else {
                result = x_add(result, path);
            }
        }
        return result;
    }
}

XValue x_test_environment_variables(void);
XValue x_test_command_line_args(void);
XValue x_test_process_operations(void);
XValue x_test_system_info(void);
XValue x_test_path_operations(void);
XValue x_test_temp_files(void);
XValue x_test_random_numbers(void);
XValue x_test_other_system_functions(void);
XValue x_main(void);

XValue x_test_environment_variables(void) {
    x_print(x_string("=== Testing Environment Variables ==="));
    XValue set_result = x_set_env(x_string("TEST_VAR"), x_string("test_value"));
    x_print(x_add(x_string("Set TEST_VAR: "), x_to_string(set_result)));
    XValue get_result = x_get_env(x_string("TEST_VAR"));
    x_print(x_add(x_string("Get TEST_VAR: "), x_to_string(get_result)));
    XValue unset_result = x_unset_env(x_string("TEST_VAR"));
    x_print(x_add(x_string("Unset TEST_VAR: "), x_to_string(unset_result)));
    XValue get_result2 = x_get_env(x_string("TEST_VAR"));
    x_print(x_add(x_string("Get deleted TEST_VAR: "), x_to_string(get_result2)));
    XValue all_vars = x_env_vars();
    x_print(x_add(x_string("Environment variables count: "), x_to_string(x_len(all_vars))));
    if (x_as_bool(x_gt(x_len(all_vars), x_int(0LL)))) {
        x_print(x_add(x_string("First environment variable: "), x_to_string(x_index_get(all_vars, x_int(0LL)))));
    }
    x_print(x_null());
    return x_null();
}

XValue x_test_command_line_args(void) {
    x_print(x_string("=== Testing Command Line Args ==="));
    XValue args_list = x_args();
    x_print(x_add(x_string("Command line args count: "), x_to_string(x_len(args_list))));
    x_print(x_add(x_string("Command line args: "), x_to_string(args_list)));
    XValue count = x_arg_count();
    x_print(x_add(x_string("arg_count(): "), x_to_string(count)));
    /* TODO: for loop */
    x_print(x_null());
    return x_null();
}

XValue x_test_process_operations(void) {
    x_print(x_string("=== Testing Process Operations ==="));
    XValue pid = x_getpid();
    x_print(x_add(x_string("Current process ID: "), x_to_string(pid)));
    XValue ppid = x_getppid();
    x_print(x_add(x_string("Parent process ID: "), x_to_string(ppid)));
    XValue system_result = x_system(x_string("echo Hello from system command"));
    x_print(x_add(x_string("system() return value: "), x_to_string(system_result)));
    XValue output_result = x_command_output(x_string("echo Hello from command_output"));
    x_print(x_add(x_string("command_output() return value: "), x_to_string(output_result)));
    x_print(x_null());
    return x_null();
}

XValue x_test_system_info(void) {
    x_print(x_string("=== Testing System Info ==="));
    XValue os = x_os_type();
    x_print(x_add(x_string("OS type: "), os));
    XValue version = x_os_version();
    x_print(x_add(x_string("OS version: "), version));
    XValue host = x_hostname();
    x_print(x_add(x_string("Hostname: "), host));
    XValue architecture = x_arch();
    x_print(x_add(x_string("Architecture: "), architecture));
    XValue free_mem = x_free_memory();
    x_print(x_add(x_add(x_string("Free memory: "), x_to_string(free_mem)), x_string(" bytes")));
    XValue total_mem = x_total_memory();
    x_print(x_add(x_add(x_string("Total memory: "), x_to_string(total_mem)), x_string(" bytes")));
    XValue cpus = x_cpu_count();
    x_print(x_add(x_string("CPU count: "), x_to_string(cpus)));
    x_print(x_null());
    return x_null();
}

XValue x_test_path_operations(void) {
    x_print(x_string("=== Testing Path Operations ==="));
    XValue current = x_current_dir();
    x_print(x_add(x_string("Current directory: "), current));
    XArray *_a = x_array_new(3);
    x_array_push(_a, x_string("dir1"));
    x_array_push(_a, x_string("dir2"));
    x_array_push(_a, x_string("file.txt"));
    XValue paths = x_array_val(_a);
    XValue joined = x_path_join(paths);
    x_print(x_add(x_string("Path join result: "), joined));
    XValue test_path = x_add(current, x_string("/test/path/file.txt"));
    XValue dirname = x_path_dirname(test_path);
    x_print(x_add(x_string("Path dirname: "), dirname));
    XValue basename = x_path_basename(test_path);
    x_print(x_add(x_string("Path basename: "), basename));
    XValue extension = x_path_extension(test_path);
    x_print(x_add(x_string("Path extension: "), extension));
    XValue exists = x_path_exists(current);
    x_print(x_add(x_string("Current directory exists: "), x_to_string(exists)));
    XValue is_file_result = x_is_file(current);
    x_print(x_add(x_string("Current directory is file: "), x_to_string(is_file_result)));
    XValue is_dir_result = x_is_dir(current);
    x_print(x_add(x_string("Current directory is dir: "), x_to_string(is_dir_result)));
    x_print(x_null());
    return x_null();
}

XValue x_test_temp_files(void) {
    x_print(x_string("=== Testing Temp Files ==="));
    XValue temp_file_result = x_temp_file();
    x_print(x_add(x_string("Create temp file: "), x_to_string(temp_file_result)));
    XValue temp_dir_result = x_temp_dir();
    x_print(x_add(x_string("Create temp dir: "), x_to_string(temp_dir_result)));
    XValue temp_dir_path = x_get_temp_dir();
    x_print(x_add(x_string("System temp dir: "), temp_dir_path));
    x_print(x_null());
    return x_null();
}

XValue x_test_random_numbers(void) {
    x_print(x_string("=== Testing Random Numbers ==="));
    x_srand(x_int(12345LL));
    x_print(x_string("Set random seed to 12345"));
    /* TODO: for loop */
    /* TODO: for loop */
    x_print(x_null());
    return x_null();
}

XValue x_test_other_system_functions(void) {
    x_print(x_string("=== Testing Other System Functions ==="));
    XValue uptime_val = x_uptime();
    x_print(x_add(x_add(x_string("System uptime: "), x_to_string(uptime_val)), x_string(" seconds")));
    XValue uid = x_getuid();
    x_print(x_add(x_string("User ID: "), x_to_string(uid)));
    XValue gid = x_getgid();
    x_print(x_add(x_string("Group ID: "), x_to_string(gid)));
    XValue username = x_get_username();
    x_print(x_add(x_string("Username: "), username));
    XValue groupname = x_get_groupname();
    x_print(x_add(x_string("Groupname: "), groupname));
    x_print(x_null());
    return x_null();
}

XValue x_main(void) {
    x_print(x_string("Starting FFI implementation test..."));
    x_print(x_string("===================================="));
    x_test_environment_variables();
    x_test_command_line_args();
    x_test_process_operations();
    x_test_system_info();
    x_test_path_operations();
    x_test_temp_files();
    x_test_random_numbers();
    x_test_other_system_functions();
    x_print(x_string("===================================="));
    x_print(x_string("System functions test completed!"));
    return x_null();
}

int main(int argc, char **argv) {
    x_main();
    return 0;
}
