// Generated by X-Lang Zig backend
// DO NOT EDIT

const std = @import("std");

const allocator = std.heap.page_allocator;

fn xEqual(a: anytype, b: @TypeOf(a)) bool {
    return if (@typeInfo(@TypeOf(a)) == .pointer)
        std.mem.eql(u8, a, b)
    else
        a == b;
}

pub fn main() void {
    _ = blk: { var map = std.StringHashMap(i32).init(std.heap.page_allocator); map.put("id", 1) catch unreachable; map.put("name", 2) catch unreachable; break :blk map; };
    std.debug.print("{s}\n", .{"Dictionary created successfully"});
}

