//! C 后端 - 将 X IR 编译为 C23 代码
//!
//! 支持完整类型映射、声明、语句和表达式生成

use std::fmt::Write;
use std::path::PathBuf;
use x_parser::ast::Program as AstProgram;

use crate::{CodeGenerator, CodegenOutput, OutputFile, FileType};

/// C 标准版本
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum CStandard {
    /// C99 标准
    C99,
    /// C11 标准
    C11,
    /// C23 标准（默认）
    #[default]
    C23,
}

impl CStandard {
    /// 获取标准的编译器标志
    pub fn flag(&self) -> &'static str {
        match self {
            CStandard::C99 => "-std=c99",
            CStandard::C11 => "-std=c11",
            CStandard::C23 => "-std=c23",
        }
    }

    /// 获取标准的字符串表示
    pub fn as_str(&self) -> &'static str {
        match self {
            CStandard::C99 => "c99",
            CStandard::C11 => "c11",
            CStandard::C23 => "c23",
        }
    }
}

/// C 后端配置
#[derive(Debug, Clone)]
pub struct CBackendConfig {
    /// 输出目录
    pub output_dir: Option<PathBuf>,
    /// 是否启用优化
    pub optimize: bool,
    /// 是否生成调试信息
    pub debug_info: bool,
    /// C 标准版本
    pub c_standard: CStandard,
    /// 是否生成头文件
    pub generate_header: bool,
}

impl Default for CBackendConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
            c_standard: CStandard::C23,
            generate_header: false,
        }
    }
}

/// C 后端错误类型
#[derive(Debug, thiserror::Error)]
pub enum CBackendError {
    #[error("代码生成错误: {0}")]
    GenerationError(String),
    #[error("I/O 错误: {0}")]
    IoError(#[from] std::io::Error),
    #[error("格式化错误: {0}")]
    FmtError(#[from] std::fmt::Error),
    #[error("不支持的特性: {0}")]
    UnsupportedFeature(String),
    #[error("类型错误: {0}")]
    TypeError(String),
}

pub type CResult<T> = Result<T, CBackendError>;

/// C 后端
pub struct CBackend {
    config: CBackendConfig,
    /// 当前缩进级别
    indent: usize,
    /// 输出缓冲区
    output: String,
    /// 需要的头文件
    needs_stdbool: bool,
    needs_stdint: bool,
    needs_stddef: bool,
    needs_stdio: bool,
    needs_stdlib: bool,
    needs_string: bool,
    /// 用户定义的类型名称（用于生成前向声明）
    user_types: Vec<String>,
    /// 全局变量名称
    global_vars: Vec<String>,
    /// 变量类型映射（名称 -> 类型）
    var_types: std::collections::HashMap<String, String>,
}

impl CBackend {
    pub fn new(config: CBackendConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
            needs_stdbool: false,
            needs_stdint: false,
            needs_stddef: false,
            needs_stdio: false,
            needs_stdlib: false,
            needs_string: false,
            user_types: Vec::new(),
            global_vars: Vec::new(),
            var_types: std::collections::HashMap::new(),
        }
    }

    /// 重置状态
    fn reset(&mut self) {
        self.indent = 0;
        self.output.clear();
        self.needs_stdbool = false;
        self.needs_stdint = false;
        self.needs_stddef = false;
        self.needs_stdio = false;
        self.needs_stdlib = false;
        self.needs_string = false;
        self.user_types.clear();
        self.global_vars.clear();
        self.var_types.clear();
    }

    /// 输出一行代码
    fn line(&mut self, s: &str) -> CResult<()> {
        if s.is_empty() {
            writeln!(self.output)?;
        } else {
            for _ in 0..self.indent {
                write!(self.output, "    ")?;
            }
            writeln!(self.output, "{}", s)?;
        }
        Ok(())
    }

    /// 生成文件头部
    fn emit_header(&mut self) -> CResult<()> {
        self.line("/* Generated by X-Lang C backend */")?;
        self.line("/* DO NOT EDIT */")?;
        self.line("")?;

        // 根据需要的类型添加头文件
        if self.needs_stdbool {
            self.line("#include <stdbool.h>")?;
        }
        if self.needs_stdint {
            self.line("#include <stdint.h>")?;
        }
        if self.needs_stddef {
            self.line("#include <stddef.h>")?;
        }
        if self.needs_stdio {
            self.line("#include <stdio.h>")?;
        }
        if self.needs_stdlib {
            self.line("#include <stdlib.h>")?;
        }
        if self.needs_string {
            self.line("#include <string.h>")?;
        }

        if self.needs_stdbool || self.needs_stdint || self.needs_stddef
            || self.needs_stdio || self.needs_stdlib || self.needs_string {
            self.line("")?;
        }

        Ok(())
    }

    /// 生成 main 函数
    fn emit_main_function(&mut self, statements: &[x_parser::ast::Statement]) -> CResult<()> {
        self.line("int main(void) {")?;
        self.indent += 1;

        if statements.is_empty() {
            self.line("/* Empty program */")?;
        } else {
            for stmt in statements {
                self.emit_statement(stmt)?;
            }
        }

        self.line("return 0;")?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// 生成语句
    fn emit_statement(&mut self, stmt: &x_parser::ast::Statement) -> CResult<()> {
        match &stmt.node {
            x_parser::ast::StatementKind::Expression(expr) => {
                let expr_str = self.emit_expression(expr)?;
                self.line(&format!("{};", expr_str))?;
            }
            x_parser::ast::StatementKind::Variable(v) => {
                self.emit_variable_decl(v)?;
            }
            x_parser::ast::StatementKind::Return(opt) => {
                match opt {
                    Some(expr) => {
                        let expr_str = self.emit_expression(expr)?;
                        self.line(&format!("return {};", expr_str))?;
                    }
                    None => {
                        self.line("return;")?;
                    }
                }
            }
            x_parser::ast::StatementKind::If(if_stmt) => {
                self.emit_if_statement(if_stmt)?;
            }
            x_parser::ast::StatementKind::While(while_stmt) => {
                self.emit_while_statement(while_stmt)?;
            }
            x_parser::ast::StatementKind::For(for_stmt) => {
                self.emit_for_statement(for_stmt)?;
            }
            x_parser::ast::StatementKind::Break => {
                self.line("break;")?;
            }
            x_parser::ast::StatementKind::Continue => {
                self.line("continue;")?;
            }
            x_parser::ast::StatementKind::DoWhile(dw) => {
                self.emit_do_while_statement(dw)?;
            }
            x_parser::ast::StatementKind::Match(m) => {
                self.emit_match_statement(m)?;
            }
            x_parser::ast::StatementKind::Try(t) => {
                self.emit_try_statement(t)?;
            }
            x_parser::ast::StatementKind::Unsafe(block) => {
                // C 不需要 unsafe 关键字，直接输出块内容
                self.line("{")?;
                self.indent += 1;
                for s in &block.statements {
                    self.emit_statement(s)?;
                }
                self.indent -= 1;
                self.line("}")?;
            }
        }
        Ok(())
    }

    /// 生成变量声明
    fn emit_variable_decl(&mut self, v: &x_parser::ast::VariableDecl) -> CResult<()> {
        let ty = if let Some(type_annot) = &v.type_annot {
            self.emit_type(type_annot)
        } else {
            // 尝试从初始化表达式推断类型
            if let Some(init) = &v.initializer {
                self.infer_type_from_expr(init)
            } else {
                "void*".to_string()
            }
        };

        // 存储变量类型
        self.var_types.insert(v.name.clone(), ty.clone());

        let init = if let Some(expr) = &v.initializer {
            let val = self.emit_expression(expr)?;
            format!(" = {}", val)
        } else {
            String::new()
        };

        let kw = if v.is_mutable { "" } else { "const " };
        self.line(&format!("{}{} {}{};", kw, ty, v.name, init))?;
        Ok(())
    }

    /// 从表达式推断类型
    fn infer_type_from_expr(&mut self, expr: &x_parser::ast::Expression) -> String {
        match &expr.node {
            x_parser::ast::ExpressionKind::Literal(lit) => {
                match lit {
                    x_parser::ast::Literal::Boolean(_) => {
                        self.needs_stdbool = true;
                        "bool".to_string()
                    }
                    x_parser::ast::Literal::Integer(_) => {
                        self.needs_stdint = true;
                        "int32_t".to_string()
                    }
                    x_parser::ast::Literal::Float(_) => "double".to_string(),
                    x_parser::ast::Literal::String(_) => "const char*".to_string(),
                    x_parser::ast::Literal::Char(_) => "char".to_string(),
                    _ => "void*".to_string(),
                }
            }
            x_parser::ast::ExpressionKind::Binary(op, lhs, _rhs) => {
                // 二元运算的类型取决于操作符和操作数
                match op {
                    // 比较运算符返回 bool
                    x_parser::ast::BinaryOp::Equal
                    | x_parser::ast::BinaryOp::NotEqual
                    | x_parser::ast::BinaryOp::Less
                    | x_parser::ast::BinaryOp::LessEqual
                    | x_parser::ast::BinaryOp::Greater
                    | x_parser::ast::BinaryOp::GreaterEqual
                    | x_parser::ast::BinaryOp::And
                    | x_parser::ast::BinaryOp::Or => {
                        self.needs_stdbool = true;
                        "bool".to_string()
                    }
                    // 算术运算符返回操作数类型
                    _ => self.infer_type_from_expr(lhs),
                }
            }
            x_parser::ast::ExpressionKind::Variable(name) => {
                // 从变量类型映射中获取类型
                if let Some(ty) = self.var_types.get(name) {
                    ty.clone()
                } else if self.global_vars.contains(name) {
                    // 已经声明过的全局变量，假设是 int32_t
                    self.needs_stdint = true;
                    "int32_t".to_string()
                } else {
                    "void*".to_string()
                }
            }
            x_parser::ast::ExpressionKind::Array(elems) => {
                // 从第一个元素推断数组元素类型
                if elems.is_empty() {
                    "void*".to_string()
                } else {
                    let elem_type = self.infer_type_from_expr(&elems[0]);
                    // 返回元素类型，稍后生成数组时会加上 []
                    format!("{}[]", elem_type)
                }
            }
            _ => "void*".to_string(),
        }
    }

    /// 生成 if 语句
    fn emit_if_statement(&mut self, if_stmt: &x_parser::ast::IfStatement) -> CResult<()> {
        let cond = self.emit_expression(&if_stmt.condition)?;
        self.line(&format!("if ({}) {{", cond))?;
        self.indent += 1;
        for stmt in &if_stmt.then_block.statements {
            self.emit_statement(stmt)?;
        }
        self.indent -= 1;

        if let Some(else_block) = &if_stmt.else_block {
            self.line("} else {")?;
            self.indent += 1;
            for stmt in &else_block.statements {
                self.emit_statement(stmt)?;
            }
            self.indent -= 1;
        }
        self.line("}")?;
        Ok(())
    }

    /// 生成 while 语句
    fn emit_while_statement(&mut self, while_stmt: &x_parser::ast::WhileStatement) -> CResult<()> {
        let cond = self.emit_expression(&while_stmt.condition)?;
        self.line(&format!("while ({}) {{", cond))?;
        self.indent += 1;
        for stmt in &while_stmt.body.statements {
            self.emit_statement(stmt)?;
        }
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// 生成 for 语句
    fn emit_for_statement(&mut self, for_stmt: &x_parser::ast::ForStatement) -> CResult<()> {
        // X 语言的 for 语句: for pattern in iterator { body }
        // 转换为 C 的索引循环
        let iter = self.emit_expression(&for_stmt.iterator)?;

        // 获取模式变量名
        let var_name = match &for_stmt.pattern {
            x_parser::ast::Pattern::Variable(name) => name.clone(),
            x_parser::ast::Pattern::Wildcard => "_".to_string(),
            _ => "item".to_string(),
        };

        // 生成 C 风格的 for 循环
        // 简化处理：使用 __i 作为索引变量
        self.line("{")?;
        self.indent += 1;
        self.needs_stddef = true;
        // 假设迭代器是数组，使用 sizeof 计算长度
        self.line(&format!("size_t __{}_len = sizeof({}) / sizeof({}[0]);", var_name, iter, iter))?;
        self.line(&format!("for (size_t __i = 0; __i < __{}_len; __i++) {{", var_name))?;
        self.indent += 1;
        // 假设数组元素类型为 int32_t
        self.needs_stdint = true;
        self.line(&format!("int32_t {} = {}[__i];", var_name, iter))?;
        for stmt in &for_stmt.body.statements {
            self.emit_statement(stmt)?;
        }
        self.indent -= 1;
        self.line("}")?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// 生成 do-while 语句
    fn emit_do_while_statement(&mut self, dw: &x_parser::ast::DoWhileStatement) -> CResult<()> {
        self.line("do {")?;
        self.indent += 1;
        for stmt in &dw.body.statements {
            self.emit_statement(stmt)?;
        }
        self.indent -= 1;
        let cond = self.emit_expression(&dw.condition)?;
        self.line(&format!("}} while ({});", cond))?;
        Ok(())
    }

    /// 生成 match 语句
    fn emit_match_statement(&mut self, match_stmt: &x_parser::ast::MatchStatement) -> CResult<()> {
        let expr = self.emit_expression(&match_stmt.expression)?;

        // 对于带标签的枚举（标签联合），生成 switch 语句
        // 对于简单枚举，也生成 switch 语句
        self.line("{")?;
        self.indent += 1;
        self.line(&format!("auto __match_val = {};", expr))?;
        self.line(&format!("switch (__match_val.tag) {{"))?;
        self.indent += 1;

        for case in &match_stmt.cases {
            // 尝试从模式中提取枚举构造器
            if let x_parser::ast::Pattern::EnumConstructor(enum_name, variant_name, patterns) = &case.pattern {
                // case 标签
                self.line(&format!("case {}_{}: {{", enum_name, variant_name))?;
                self.indent += 1;

                // 如果变体有负载，需要绑定到模式变量
                if !patterns.is_empty() {
                    // 将负载数据提取到变量
                    match patterns.len() {
                        0 => {},
                        1 => {
                            if let x_parser::ast::Pattern::Variable(var_name) = &patterns[0] {
                                // 单个变量绑定
                                self.line(&format!("{} = __match_val.data.{};", var_name, variant_name))?;
                            }
                        }
                        _ => {
                            // 多个元素的元组，逐个绑定
                            for (i, pattern) in patterns.iter().enumerate() {
                                if let x_parser::ast::Pattern::Variable(var_name) = pattern {
                                    self.line(&format!("{} = __match_val.data.{}.f{};", var_name, variant_name, i))?;
                                }
                            }
                        }
                    }
                }

                // 处理匹配守卫 - guard 在 switch case 中需要额外判断
                if let Some(guard) = &case.guard {
                    let guard_expr = self.emit_expression(guard)?;
                    self.line(&format!("if (!{}) {{ break; }}", guard_expr))?;
                }

                // 输出 case 体
                for stmt in &case.body.statements {
                    self.emit_statement(stmt)?;
                }

                // break 跳出 switch
                self.line("break;")?;

                self.indent -= 1;
                self.line("}")?;
            } else if let x_parser::ast::Pattern::Wildcard = case.pattern {
                // 通配符作为 default case
                self.line("default: {")?;
                self.indent += 1;
                for stmt in &case.body.statements {
                    self.emit_statement(stmt)?;
                }
                self.indent -= 1;
                self.line("}")?;
            } else {
                // 其他模式暂时保留注释占位
                self.line("// Unsupported pattern")?;
            }
        }

        self.indent -= 1;
        self.line("}")?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// 生成 try 语句
    fn emit_try_statement(&mut self, try_stmt: &x_parser::ast::TryStatement) -> CResult<()> {
        // 简化处理：try-catch 转换为基本块
        self.line("/* try { */")?;
        for stmt in &try_stmt.body.statements {
            self.emit_statement(stmt)?;
        }

        for catch in &try_stmt.catch_clauses {
            self.line(&format!("/* catch ({}) */ {{", catch.exception_type.as_ref().unwrap_or(&"".to_string())))?;
            for stmt in &catch.body.statements {
                self.emit_statement(stmt)?;
            }
            self.line("}")?;
        }

        if let Some(finally) = &try_stmt.finally_block {
            self.line("/* finally */ {")?;
            for stmt in &finally.statements {
                self.emit_statement(stmt)?;
            }
            self.line("}")?;
        }
        Ok(())
    }

    /// 从 AST 生成 C 代码
    fn generate_c_from_ast(&mut self, program: &AstProgram) -> CResult<String> {
        self.reset();

        // 预扫描以确定需要的头文件
        self.scan_program(program)?;

        // 生成头部
        self.emit_header()?;

        // 生成声明
        for decl in &program.declarations {
            self.emit_declaration(decl)?;
        }

        // 如果没有 main 函数，生成默认 main
        let has_main = program.declarations.iter().any(|d| {
            matches!(d, x_parser::ast::Declaration::Function(f) if f.name == "main")
        });

        if !has_main {
            self.line("")?;
            self.emit_main_function(&program.statements)?;
        }

        Ok(self.output.clone())
    }

    /// 预扫描程序以确定需要的头文件
    fn scan_program(&mut self, program: &AstProgram) -> CResult<()> {
        // 扫描声明
        for decl in &program.declarations {
            self.scan_declaration(decl)?;
        }

        // 扫描顶层语句
        for stmt in &program.statements {
            self.scan_statement(stmt)?;
        }

        Ok(())
    }

    /// 扫描声明
    fn scan_declaration(&mut self, decl: &x_parser::ast::Declaration) -> CResult<()> {
        match decl {
            x_parser::ast::Declaration::Function(f) => {
                // 检查返回类型和参数类型
                if let Some(ret_type) = &f.return_type {
                    self.scan_type(ret_type);
                }
                for param in &f.parameters {
                    if let Some(type_annot) = &param.type_annot {
                        self.scan_type(type_annot);
                    }
                }
                // 扫描函数体
                for stmt in &f.body.statements {
                    self.scan_statement(stmt)?;
                }
            }
            x_parser::ast::Declaration::Variable(v) => {
                if let Some(type_annot) = &v.type_annot {
                    self.scan_type(type_annot);
                }
                if let Some(init) = &v.initializer {
                    self.scan_expression(init)?;
                }
            }
            _ => {}
        }
        Ok(())
    }

    /// 扫描语句
    fn scan_statement(&mut self, stmt: &x_parser::ast::Statement) -> CResult<()> {
        match &stmt.node {
            x_parser::ast::StatementKind::Expression(expr) => {
                self.scan_expression(expr)?;
            }
            x_parser::ast::StatementKind::Variable(v) => {
                if let Some(type_annot) = &v.type_annot {
                    self.scan_type(type_annot);
                }
                if let Some(init) = &v.initializer {
                    self.scan_expression(init)?;
                }
            }
            x_parser::ast::StatementKind::Return(Some(expr)) => {
                self.scan_expression(expr)?;
            }
            _ => {}
        }
        Ok(())
    }

    /// 扫描表达式
    fn scan_expression(&mut self, expr: &x_parser::ast::Expression) -> CResult<()> {
        match &expr.node {
            x_parser::ast::ExpressionKind::Literal(lit) => {
                match lit {
                    x_parser::ast::Literal::Boolean(_) => self.needs_stdbool = true,
                    x_parser::ast::Literal::Integer(_) => self.needs_stdint = true,
                    x_parser::ast::Literal::String(_) => {
                        self.needs_stdio = true;
                        self.needs_stddef = true;
                    }
                    _ => {}
                }
            }
            x_parser::ast::ExpressionKind::Call(callee, args) => {
                // 检查是否是内置打印函数
                if let x_parser::ast::ExpressionKind::Variable(func_name) = &callee.node {
                    if func_name == "println" || func_name == "print" || func_name == "print_inline" {
                        self.needs_stdio = true;
                    }
                }
                self.scan_expression(callee)?;
                for arg in args {
                    self.scan_expression(arg)?;
                }
            }
            _ => {}
        }
        Ok(())
    }

    /// 扫描类型
    fn scan_type(&mut self, ty: &x_parser::ast::Type) {
        match ty {
            x_parser::ast::Type::Bool => self.needs_stdbool = true,
            x_parser::ast::Type::Int | x_parser::ast::Type::UnsignedInt => self.needs_stdint = true,
            x_parser::ast::Type::String => {
                self.needs_stddef = true; // for size_t
            }
            _ => {}
        }
    }

    /// 生成声明
    fn emit_declaration(&mut self, decl: &x_parser::ast::Declaration) -> CResult<()> {
        match decl {
            x_parser::ast::Declaration::Function(f) => self.emit_function(f),
            x_parser::ast::Declaration::Variable(v) => self.emit_global_variable(v),
            x_parser::ast::Declaration::ExternFunction(e) => self.emit_extern_function(e),
            x_parser::ast::Declaration::Class(c) => self.emit_class(c),
            x_parser::ast::Declaration::Trait(t) => self.emit_trait(t),
            x_parser::ast::Declaration::Enum(e) => self.emit_enum(e),
            x_parser::ast::Declaration::TypeAlias(t) => self.emit_type_alias(t),
            x_parser::ast::Declaration::Import(_) => Ok(()), // 忽略导入
            x_parser::ast::Declaration::Module(_) => Ok(()), // 忽略模块
            x_parser::ast::Declaration::Export(_) => Ok(()), // 忽略导出
        }
    }

    /// 生成函数
    fn emit_function(&mut self, f: &x_parser::ast::FunctionDecl) -> CResult<()> {
        // 生成返回类型
        let return_type = if let Some(ret_type) = &f.return_type {
            self.emit_type(ret_type)
        } else {
            "void".to_string()
        };

        // 生成参数列表
        let params = if f.parameters.is_empty() {
            "void".to_string()
        } else {
            f.parameters
                .iter()
                .map(|p| {
                    let ty = if let Some(type_annot) = &p.type_annot {
                        self.emit_type(type_annot)
                    } else {
                        "void*".to_string()
                    };
                    format!("{} {}", ty, p.name)
                })
                .collect::<Vec<_>>()
                .join(", ")
        };

        // 函数签名
        self.line(&format!("{} {}({}) {{", return_type, f.name, params))?;
        self.indent += 1;

        // 函数体
        for stmt in &f.body.statements {
            self.emit_statement(stmt)?;
        }

        // 如果没有显式返回，添加默认返回
        if f.return_type.is_none() {
            self.line("return;")?;
        }

        self.indent -= 1;
        self.line("}")?;
        self.line("")?;

        Ok(())
    }

    /// 生成全局变量
    fn emit_global_variable(&mut self, v: &x_parser::ast::VariableDecl) -> CResult<()> {
        let ty = if let Some(type_annot) = &v.type_annot {
            self.emit_type(type_annot)
        } else if let Some(init) = &v.initializer {
            // 从初始化表达式推断类型
            self.infer_type_from_expr(init)
        } else {
            "void*".to_string()
        };

        // 存储变量类型（去掉 [] 后缀用于后续引用）
        let base_ty = ty.trim_end_matches("[]").to_string();
        self.var_types.insert(v.name.clone(), base_ty.clone());

        let init = if let Some(expr) = &v.initializer {
            let val = self.emit_expression(expr)?;
            format!(" = {}", val)
        } else {
            String::new()
        };

        let kw = if v.is_mutable { "" } else { "const " };

        // 特殊处理数组类型
        if ty.ends_with("[]") {
            // 数组声明: const int32_t name[] = {...}
            self.line(&format!("{}{} {}[]{};", kw, base_ty, v.name, init))?;
        } else {
            self.line(&format!("{}{} {}{};", kw, ty, v.name, init))?;
        }
        self.global_vars.push(v.name.clone());

        Ok(())
    }

    /// 生成外部函数声明
    fn emit_extern_function(&mut self, e: &x_parser::ast::ExternFunctionDecl) -> CResult<()> {
        let return_type = if let Some(ret_type) = &e.return_type {
            self.emit_type(ret_type)
        } else {
            "void".to_string()
        };

        let params = if e.parameters.is_empty() {
            "void".to_string()
        } else {
            e.parameters
                .iter()
                .map(|p| {
                    let ty = if let Some(type_annot) = &p.type_annot {
                        self.emit_type(type_annot)
                    } else {
                        "void*".to_string()
                    };
                    format!("{} {}", ty, p.name)
                })
                .collect::<Vec<_>>()
                .join(", ")
        };

        self.line(&format!("extern {} {}({});", return_type, e.name, params))?;
        self.line("")?;

        Ok(())
    }

    /// 生成类
    fn emit_class(&mut self, _c: &x_parser::ast::ClassDecl) -> CResult<()> {
        // TODO: 实现类生成
        Ok(())
    }

    /// 生成 Trait
    fn emit_trait(&mut self, _t: &x_parser::ast::TraitDecl) -> CResult<()> {
        // TODO: 实现 trait 生成
        Ok(())
    }

    /// 检查枚举是否至少有一个带负载的变体
    fn has_any_payload_variant(&self, e: &x_parser::ast::EnumDecl) -> bool {
        e.variants.iter().any(|v| !matches!(v.data, x_parser::ast::EnumVariantData::Unit))
    }

    /// 生成标签枚举（判别式）
    fn emit_tag_enum(&mut self, e: &x_parser::ast::EnumDecl) -> CResult<()> {
        self.line(&format!("typedef enum {{"))?;
        self.indent += 1;

        for (i, variant) in e.variants.iter().enumerate() {
            let value = i.to_string();
            self.line(&format!("{}_{} = {},", e.name, variant.name, value))?;
        }

        self.indent -= 1;
        self.line(&format!("}} {}_Tag;", e.name))?;
        self.line("")?;
        Ok(())
    }

    /// 生成联合类型用于存储变体数据
    fn emit_union_for_variants(&mut self, e: &x_parser::ast::EnumDecl) -> CResult<()> {
        self.line(&format!("typedef union {{"))?;
        self.indent += 1;

        for variant in &e.variants {
            match &variant.data {
                x_parser::ast::EnumVariantData::Unit => {
                    // 单元变体不需要存储数据
                }
                x_parser::ast::EnumVariantData::Tuple(types) => {
                    if types.len() == 1 {
                        // 单元素元组，直接使用该类型
                        let ty = self.emit_type(&types[0]);
                        self.line(&format!("{} {};", ty, variant.name))?;
                    } else {
                        // 多元素元组，需要包装成结构体
                        // C 联合不能直接存放多个不同大小的字段，所以用结构体包装
                        self.line(&format!("struct {{"))?;
                        self.indent += 1;
                        for (i, ty) in types.iter().enumerate() {
                            let c_ty = self.emit_type(ty);
                            self.line(&format!("{} f{};", c_ty, i))?;
                        }
                        self.indent -= 1;
                        self.line(&format!("}} {};", variant.name))?;
                    }
                }
                x_parser::ast::EnumVariantData::Record(fields) => {
                    // 记录变体，每个字段都在结构体中
                    self.line(&format!("struct {{"))?;
                    self.indent += 1;
                    for (name, ty) in fields {
                        let c_ty = self.emit_type(ty);
                        self.line(&format!("{} {};", c_ty, name))?;
                    }
                    self.indent -= 1;
                    self.line(&format!("}} {};", variant.name))?;
                }
            }
        }

        self.indent -= 1;
        self.line(&format!("}} {}_Union;", e.name))?;
        self.line("")?;
        Ok(())
    }

    /// 生成包含标签和联合的完整结构体
    fn emit_combined_struct(&mut self, e: &x_parser::ast::EnumDecl) -> CResult<()> {
        self.line(&format!("typedef struct {{"))?;
        self.indent += 1;
        self.line(&format!("{}_Tag tag;", e.name))?;
        self.line(&format!("{}_Union data;", e.name))?;
        self.indent -= 1;
        self.line(&format!("}} {};", e.name))?;
        self.line("")?;
        Ok(())
    }

    /// 生成枚举
    fn emit_enum(&mut self, e: &x_parser::ast::EnumDecl) -> CResult<()> {
        if self.has_any_payload_variant(e) {
            // 至少有一个变体带负载：生成标签联合结构
            self.emit_tag_enum(e)?;
            self.emit_union_for_variants(e)?;
            self.emit_combined_struct(e)?;
        } else {
            // 所有变体都是单元变体：保持原有行为
            self.line(&format!("typedef enum {{"))?;
            self.indent += 1;

            for (i, variant) in e.variants.iter().enumerate() {
                let value = i.to_string();
                self.line(&format!("{}_{} = {},", e.name, variant.name, value))?;
            }

            self.indent -= 1;
            self.line(&format!("}} {};", e.name))?;
            self.line("")?;
        }

        Ok(())
    }

    /// 生成类型别名
    fn emit_type_alias(&mut self, t: &x_parser::ast::TypeAlias) -> CResult<()> {
        let target = self.emit_type(&t.type_);
        self.line(&format!("typedef {} {};", target, t.name))?;
        self.line("")?;
        Ok(())
    }

    /// 生成类型字符串
    fn emit_type(&mut self, ty: &x_parser::ast::Type) -> String {
        match ty {
            x_parser::ast::Type::Bool => {
                self.needs_stdbool = true;
                "bool".to_string()
            }
            x_parser::ast::Type::Int => {
                self.needs_stdint = true;
                "int32_t".to_string()
            }
            x_parser::ast::Type::UnsignedInt => {
                self.needs_stdint = true;
                "uint32_t".to_string()
            }
            x_parser::ast::Type::Float => "double".to_string(),
            x_parser::ast::Type::String => {
                self.needs_stddef = true;
                "const char*".to_string()
            }
            x_parser::ast::Type::Char => "char32_t".to_string(),
            x_parser::ast::Type::Void => "void".to_string(),
            x_parser::ast::Type::Unit => "void".to_string(),
            x_parser::ast::Type::Never => "void".to_string(),
            x_parser::ast::Type::Option(inner) => {
                let inner_str = self.emit_type(inner);
                format!("{}*", inner_str) // 简化处理
            }
            x_parser::ast::Type::Array(inner) => {
                let inner_str = self.emit_type(inner);
                format!("{}*", inner_str) // 简化处理
            }
            x_parser::ast::Type::Pointer(inner) => {
                let inner_str = self.emit_type(inner);
                format!("{}*", inner_str)
            }
            x_parser::ast::Type::ConstPointer(inner) => {
                let inner_str = self.emit_type(inner);
                format!("const {}*", inner_str)
            }
            x_parser::ast::Type::Generic(name) => name.clone(),
            x_parser::ast::Type::TypeConstructor(name, args) => {
                // 将类型参数编码到名称中，例如 Option<i32> → option_i32_t
                if args.is_empty() {
                    format!("{}_t", name.to_lowercase())
                } else {
                    let args_str = args
                        .iter()
                        .map(|ty| self.emit_type(ty))
                        .collect::<Vec<_>>()
                        .join("_");
                    format!("{}_{}_{}", name.to_lowercase(), args_str, "t")
                }
            }
            x_parser::ast::Type::TypeParam(name) => name.clone(),
            // C FFI 类型
            x_parser::ast::Type::CInt => "int".to_string(),
            x_parser::ast::Type::CUInt => "unsigned int".to_string(),
            x_parser::ast::Type::CLong => "long".to_string(),
            x_parser::ast::Type::CULong => "unsigned long".to_string(),
            x_parser::ast::Type::CLongLong => "long long".to_string(),
            x_parser::ast::Type::CULongLong => "unsigned long long".to_string(),
            x_parser::ast::Type::CFloat => "float".to_string(),
            x_parser::ast::Type::CDouble => "double".to_string(),
            x_parser::ast::Type::CChar => "char".to_string(),
            x_parser::ast::Type::CSize => {
                self.needs_stddef = true;
                "size_t".to_string()
            }
            x_parser::ast::Type::CString => "char*".to_string(),
            _ => "void*".to_string(), // 默认处理
        }
    }

    /// 生成表达式字符串
    fn emit_expression(&mut self, expr: &x_parser::ast::Expression) -> CResult<String> {
        match &expr.node {
            x_parser::ast::ExpressionKind::Literal(lit) => self.emit_literal(lit),
            x_parser::ast::ExpressionKind::Variable(name) => Ok(name.clone()),
            x_parser::ast::ExpressionKind::Binary(op, lhs, rhs) => {
                let l = self.emit_expression(lhs)?;
                let r = self.emit_expression(rhs)?;
                let op_str = self.emit_binary_op(op);
                Ok(format!("({} {} {})", l, op_str, r))
            }
            x_parser::ast::ExpressionKind::Unary(op, e) => {
                let operand = self.emit_expression(e)?;
                let op_str = match op {
                    x_parser::ast::UnaryOp::Negate => "-",
                    x_parser::ast::UnaryOp::Not => "!",
                    x_parser::ast::UnaryOp::BitNot => "~",
                    _ => "",
                };
                Ok(format!("({}{})", op_str, operand))
            }
            x_parser::ast::ExpressionKind::Call(callee, args) => {
                // 检查是否是内置函数
                if let x_parser::ast::ExpressionKind::Variable(func_name) = &callee.node {
                    match func_name.as_str() {
                        "println" | "print" => {
                            self.needs_stdio = true;
                            if args.is_empty() {
                                return Ok("printf(\"\\n\")".to_string());
                            }
                            let arg = self.emit_expression(&args[0])?;
                            // 检查是否是字符串字面量
                            if arg.starts_with('"') {
                                if func_name == "println" {
                                    Ok(format!("printf(\"%s\\n\", {})", arg))
                                } else {
                                    Ok(format!("printf(\"%s\", {})", arg))
                                }
                            } else {
                                // 对于整数，使用 %d
                                if func_name == "println" {
                                    Ok(format!("printf(\"%d\\n\", {})", arg))
                                } else {
                                    Ok(format!("printf(\"%d\", {})", arg))
                                }
                            }
                        }
                        "print_inline" => {
                            self.needs_stdio = true;
                            if args.is_empty() {
                                return Ok("printf(\"\")".to_string());
                            }
                            let arg = self.emit_expression(&args[0])?;
                            if arg.starts_with('"') {
                                Ok(format!("printf(\"%s\", {})", arg))
                            } else {
                                Ok(format!("printf(\"%d\", {})", arg))
                            }
                        }
                        _ => {
                            // 普通函数调用
                            let args_str: Vec<String> = args
                                .iter()
                                .map(|a| self.emit_expression(a))
                                .collect::<CResult<Vec<_>>>()?;
                            Ok(format!("{}({})", func_name, args_str.join(", ")))
                        }
                    }
                } else {
                    let func = self.emit_expression(callee)?;
                    let args_str: Vec<String> = args
                        .iter()
                        .map(|a| self.emit_expression(a))
                        .collect::<CResult<Vec<_>>>()?;
                    Ok(format!("{}({})", func, args_str.join(", ")))
                }
            }
            x_parser::ast::ExpressionKind::Member(obj, field) => {
                let obj_str = self.emit_expression(obj)?;
                Ok(format!("{}.{}", obj_str, field))
            }
            x_parser::ast::ExpressionKind::Assign(target, value) => {
                let target_str = self.emit_expression(target)?;
                let value_str = self.emit_expression(value)?;
                Ok(format!("{} = {}", target_str, value_str))
            }
            x_parser::ast::ExpressionKind::Array(elems) => {
                // 生成 C 数组字面量初始化语法
                let elem_strs: Vec<String> = elems
                    .iter()
                    .map(|e| self.emit_expression(e))
                    .collect::<CResult<Vec<_>>>()?;
                Ok(format!("{{ {} }}", elem_strs.join(", ")))
            }
            x_parser::ast::ExpressionKind::Dictionary(pairs) => {
                // 简化处理：字典不支持直接 C 语法
                // 生成注释标记
                Ok(format!("/* dictionary with {} entries */", pairs.len()))
            }
            x_parser::ast::ExpressionKind::Range(start, end, inclusive) => {
                let start_str = self.emit_expression(start)?;
                let end_str = self.emit_expression(end)?;
                let op = if *inclusive { "..=" } else { ".." };
                Ok(format!("/* range {} {} {} */", start_str, op, end_str))
            }
            x_parser::ast::ExpressionKind::If(cond, then_expr, else_expr) => {
                let cond_str = self.emit_expression(cond)?;
                let then_str = self.emit_expression(then_expr)?;
                let else_str = self.emit_expression(else_expr)?;
                Ok(format!("({} ? {} : {})", cond_str, then_str, else_str))
            }
            _ => Ok("/* unsupported expression */".to_string()),
        }
    }

    /// 生成字面量
    fn emit_literal(&mut self, lit: &x_parser::ast::Literal) -> CResult<String> {
        match lit {
            x_parser::ast::Literal::Boolean(b) => {
                self.needs_stdbool = true;
                Ok(b.to_string())
            }
            x_parser::ast::Literal::Integer(n) => {
                self.needs_stdint = true;
                Ok(n.to_string())  // 纯数字，不带后缀
            }
            x_parser::ast::Literal::Float(f) => Ok(f.to_string()),
            x_parser::ast::Literal::String(s) => {
                let escaped = s
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('\n', "\\n")
                    .replace('\r', "\\r")
                    .replace('\t', "\\t");
                Ok(format!("\"{}\"", escaped))
            }
            x_parser::ast::Literal::Char(c) => Ok(format!("'{}'", c)),
            x_parser::ast::Literal::Null => Ok("NULL".to_string()),
            x_parser::ast::Literal::None => Ok("NULL".to_string()),
            x_parser::ast::Literal::Unit => Ok("0".to_string()),
        }
    }

    /// 生成二元运算符
    fn emit_binary_op(&mut self, op: &x_parser::ast::BinaryOp) -> &'static str {
        match op {
            x_parser::ast::BinaryOp::Add => "+",
            x_parser::ast::BinaryOp::Sub => "-",
            x_parser::ast::BinaryOp::Mul => "*",
            x_parser::ast::BinaryOp::Div => "/",
            x_parser::ast::BinaryOp::Mod => "%",
            x_parser::ast::BinaryOp::Equal => "==",
            x_parser::ast::BinaryOp::NotEqual => "!=",
            x_parser::ast::BinaryOp::Less => "<",
            x_parser::ast::BinaryOp::LessEqual => "<=",
            x_parser::ast::BinaryOp::Greater => ">",
            x_parser::ast::BinaryOp::GreaterEqual => ">=",
            x_parser::ast::BinaryOp::And => "&&",
            x_parser::ast::BinaryOp::Or => "||",
            x_parser::ast::BinaryOp::BitAnd => "&",
            x_parser::ast::BinaryOp::BitOr => "|",
            x_parser::ast::BinaryOp::BitXor => "^",
            x_parser::ast::BinaryOp::LeftShift => "<<",
            x_parser::ast::BinaryOp::RightShift => ">>",
            _ => "/* unknown op */",
        }
    }
}

/// 实现 CodeGenerator trait
impl CodeGenerator for CBackend {
    type Config = CBackendConfig;
    type Error = CBackendError;

    fn new(config: Self::Config) -> Self {
        Self::new(config)
    }

    fn generate_from_ast(&mut self, program: &AstProgram) -> Result<CodegenOutput, Self::Error> {
        let c_code = self.generate_c_from_ast(program)?;

        let output_file = OutputFile {
            path: PathBuf::from("output.c"),
            content: c_code.into_bytes(),
            file_type: FileType::C,
        };

        Ok(CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }

    fn generate_from_hir(&mut self, _hir: &x_hir::Hir) -> Result<CodegenOutput, Self::Error> {
        // TODO: 实现 HIR 到 C 的生成
        Err(CBackendError::UnsupportedFeature(
            "HIR generation not yet implemented".to_string(),
        ))
    }

    fn generate_from_lir(&mut self, lir: &x_lir::Program) -> Result<CodegenOutput, Self::Error> {
        self.reset();

        // First, scan the program to determine required headers
        self.scan_lir_program(lir);

        // Emit standard headers (always include basic types)
        self.needs_stdbool = true;
        self.needs_stdint = true;
        self.needs_stddef = true;
        self.emit_header()?;

        // Emit all declarations
        for decl in &lir.declarations {
            self.emit_lir_declaration(decl)?;
            self.line("")?;
        }

        // Check if we have a main function
        let has_main = lir.declarations.iter().any(|d| {
            matches!(d, x_lir::Declaration::Function(f) if f.name == "main")
        });

        // If no main function and program has no declarations except maybe others,
        // we don't add anything - assume the user handles it
        if !has_main && lir.declarations.iter().all(|d| !matches!(d, x_lir::Declaration::Function(_))) {
            // Add empty main for compatibility
            self.line("int main(void) {")?;
            self.indent += 1;
            self.line("return 0;")?;
            self.indent -= 1;
            self.line("}")?;
        }

        let output_file = OutputFile {
            path: PathBuf::from("output.c"),
            content: self.output.clone().into_bytes(),
            file_type: FileType::C,
        };

        Ok(CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }
}

impl CBackend {
    /// Scan LIR program to determine required headers
    fn scan_lir_program(&mut self, lir: &x_lir::Program) {
        for decl in &lir.declarations {
            if let x_lir::Declaration::Function(f) = decl {
                self.scan_lir_function(f);
            }
        }
    }

    /// Scan LIR function for required headers
    fn scan_lir_function(&mut self, f: &x_lir::Function) {
        for stmt in &f.body.statements {
            self.scan_lir_statement(stmt);
        }
    }

    /// Scan LIR statement for required headers
    fn scan_lir_statement(&mut self, stmt: &x_lir::Statement) {
        match stmt {
            x_lir::Statement::Expression(expr) => self.scan_lir_expression(expr),
            x_lir::Statement::Variable(var) => {
                if let Some(init) = &var.initializer {
                    self.scan_lir_expression(init);
                }
            }
            x_lir::Statement::Return(Some(expr)) => self.scan_lir_expression(expr),
            x_lir::Statement::Compound(block) => {
                for s in &block.statements {
                    self.scan_lir_statement(s);
                }
            }
            x_lir::Statement::If(if_stmt) => {
                self.scan_lir_expression(&if_stmt.condition);
                self.scan_lir_statement(&if_stmt.then_branch);
                if let Some(else_branch) = &if_stmt.else_branch {
                    self.scan_lir_statement(else_branch);
                }
            }
            x_lir::Statement::While(while_stmt) => {
                self.scan_lir_expression(&while_stmt.condition);
                self.scan_lir_statement(&while_stmt.body);
            }
            x_lir::Statement::DoWhile(do_while) => {
                self.scan_lir_expression(&do_while.condition);
                self.scan_lir_statement(&do_while.body);
            }
            x_lir::Statement::For(for_stmt) => {
                if let Some(init) = &for_stmt.initializer {
                    self.scan_lir_statement(init);
                }
                if let Some(cond) = &for_stmt.condition {
                    self.scan_lir_expression(cond);
                }
                if let Some(inc) = &for_stmt.increment {
                    self.scan_lir_expression(inc);
                }
                self.scan_lir_statement(&for_stmt.body);
            }
            _ => {}
        }
    }

    /// Scan LIR expression for required headers
    fn scan_lir_expression(&mut self, expr: &x_lir::Expression) {
        match expr {
            x_lir::Expression::Call(func, args) => {
                // Check for builtin functions that need headers
                if let x_lir::Expression::Variable(func_name) = func.as_ref() {
                    match func_name.as_str() {
                        "println" | "print" | "print_inline" => {
                            self.needs_stdio = true;
                        }
                        "exit" => {
                            self.needs_stdlib = true;
                        }
                        _ => {}
                    }
                }
                // Scan the function and arguments
                self.scan_lir_expression(func);
                for arg in args {
                    self.scan_lir_expression(arg);
                }
            }
            x_lir::Expression::Binary(_, lhs, rhs) => {
                self.scan_lir_expression(lhs);
                self.scan_lir_expression(rhs);
            }
            x_lir::Expression::Unary(_, e) => {
                self.scan_lir_expression(e);
            }
            x_lir::Expression::Assign(target, value) => {
                self.scan_lir_expression(target);
                self.scan_lir_expression(value);
            }
            x_lir::Expression::Member(obj, _) => {
                self.scan_lir_expression(obj);
            }
            x_lir::Expression::Index(arr, idx) => {
                self.scan_lir_expression(arr);
                self.scan_lir_expression(idx);
            }
            x_lir::Expression::Ternary(cond, then_expr, else_expr) => {
                self.scan_lir_expression(cond);
                self.scan_lir_expression(then_expr);
                self.scan_lir_expression(else_expr);
            }
            _ => {}
        }
    }

    /// Emit LIR declaration
    fn emit_lir_declaration(&mut self, decl: &x_lir::Declaration) -> CResult<()> {
        match decl {
            x_lir::Declaration::Function(f) => self.emit_lir_function(f),
            x_lir::Declaration::Global(g) => self.emit_lir_global(g),
            x_lir::Declaration::Struct(s) => self.emit_lir_struct(s),
            x_lir::Declaration::Class(c) => self.emit_lir_class(c),
            x_lir::Declaration::VTable(v) => self.emit_lir_vtable(v),
            x_lir::Declaration::Enum(e) => self.emit_lir_enum(e),
            x_lir::Declaration::TypeAlias(t) => self.emit_lir_type_alias(t),
            x_lir::Declaration::ExternFunction(e) => self.emit_lir_extern_function(e),
        }
    }

    /// Emit LIR function
    fn emit_lir_function(&mut self, f: &x_lir::Function) -> CResult<()> {
        let return_type = self.emit_lir_type(&f.return_type);

        let params = if f.parameters.is_empty() {
            "void".to_string()
        } else {
            f.parameters
                .iter()
                .map(|p| format!("{} {}", self.emit_lir_type(&p.type_), p.name))
                .collect::<Vec<_>>()
                .join(", ")
        };

        self.line(&format!("{} {}({}) {{", return_type, f.name, params))?;
        self.indent += 1;

        // Emit function body
        for stmt in &f.body.statements {
            self.emit_lir_statement(stmt)?;
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    /// Emit LIR statement
    fn emit_lir_statement(&mut self, stmt: &x_lir::Statement) -> CResult<()> {
        match stmt {
            x_lir::Statement::Expression(expr) => {
                let expr_str = self.emit_lir_expression(expr)?;
                self.line(&format!("{};", expr_str))?;
            }
            x_lir::Statement::Variable(var) => {
                let ty = self.emit_lir_type(&var.type_);
                let init = if let Some(init_expr) = &var.initializer {
                    format!(" = {}", self.emit_lir_expression(init_expr)?)
                } else {
                    String::new()
                };
                self.line(&format!("{} {}{};", ty, var.name, init))?;
            }
            x_lir::Statement::Return(Some(expr)) => {
                let expr_str = self.emit_lir_expression(expr)?;
                self.line(&format!("return {};", expr_str))?;
            }
            x_lir::Statement::Return(None) => {
                self.line("return;")?;
            }
            x_lir::Statement::Label(label) => {
                self.line(&format!("{}:", label))?;
            }
            x_lir::Statement::Break => self.line("break;")?,
            x_lir::Statement::Continue => self.line("continue;")?,
            x_lir::Statement::Empty => {}
            x_lir::Statement::Compound(block) => {
                self.line("{")?;
                self.indent += 1;
                for s in &block.statements {
                    self.emit_lir_statement(s)?;
                }
                self.indent -= 1;
                self.line("}")?;
            }
            x_lir::Statement::If(if_stmt) => {
                let cond = self.emit_lir_expression(&if_stmt.condition)?;
                self.line(&format!("if ({}) {{", cond))?;
                self.indent += 1;
                self.emit_lir_statement(&if_stmt.then_branch)?;
                self.indent -= 1;
                if let Some(else_branch) = &if_stmt.else_branch {
                    self.line("} else {")?;
                    self.indent += 1;
                    self.emit_lir_statement(else_branch)?;
                    self.indent -= 1;
                }
                self.line("}")?;
            }
            x_lir::Statement::While(while_stmt) => {
                let cond = self.emit_lir_expression(&while_stmt.condition)?;
                self.line(&format!("while ({}) {{", cond))?;
                self.indent += 1;
                self.emit_lir_statement(&while_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            x_lir::Statement::DoWhile(do_while) => {
                self.line("do {")?;
                self.indent += 1;
                self.emit_lir_statement(&do_while.body)?;
                self.indent -= 1;
                let cond = self.emit_lir_expression(&do_while.condition)?;
                self.line(&format!("}} while ({});", cond))?;
            }
            x_lir::Statement::For(for_stmt) => {
                self.line("for (")?;
                if let Some(init) = &for_stmt.initializer {
                    let init_str = match init.as_ref() {
                        x_lir::Statement::Variable(v) => {
                            let ty = self.emit_lir_type(&v.type_);
                            let init = if let Some(e) = &v.initializer {
                                format!(" = {}", self.emit_lir_expression(e)?)
                            } else {
                                String::new()
                            };
                            format!("{} {}{}", ty, v.name, init)
                        }
                        x_lir::Statement::Expression(expr) => {
                            self.emit_lir_expression(expr)?
                        }
                        _ => String::new(),
                    };
                    write!(self.output, "{}", init_str)?;
                }
                write!(self.output, "; ")?;
                if let Some(cond) = &for_stmt.condition {
                    let cond_str = self.emit_lir_expression(cond)?;
                    write!(self.output, "{}", cond_str)?;
                }
                write!(self.output, "; ")?;
                if let Some(inc) = &for_stmt.increment {
                    let inc_str = self.emit_lir_expression(inc)?;
                    write!(self.output, "{}", inc_str)?;
                }
                writeln!(self.output, ") {{")?;
                self.indent += 1;
                self.emit_lir_statement(&for_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            _ => {
                // Fallback for other statement types
                self.line(&format!("/* TODO: {} */", stmt))?;
            }
        }
        Ok(())
    }

    /// Emit LIR expression
    fn emit_lir_expression(&mut self, expr: &x_lir::Expression) -> CResult<String> {
        match expr {
            x_lir::Expression::Literal(lit) => self.emit_lir_literal(lit),
            x_lir::Expression::Variable(name) => Ok(name.clone()),
            x_lir::Expression::Unary(op, e) => {
                let operand = self.emit_lir_expression(e)?;
                let op_str = match op {
                    x_lir::UnaryOp::Plus => "+",
                    x_lir::UnaryOp::Minus => "-",
                    x_lir::UnaryOp::Not => "!",
                    x_lir::UnaryOp::BitNot => "~",
                    x_lir::UnaryOp::PreIncrement => "++",
                    x_lir::UnaryOp::PreDecrement => "--",
                    x_lir::UnaryOp::PostIncrement => "++",
                    x_lir::UnaryOp::PostDecrement => "--",
                };
                match op {
                    x_lir::UnaryOp::PostIncrement | x_lir::UnaryOp::PostDecrement => {
                        Ok(format!("{}{}", operand, op_str))
                    }
                    _ => Ok(format!("{}{}", op_str, operand)),
                }
            }
            x_lir::Expression::Binary(op, lhs, rhs) => {
                let left = self.emit_lir_expression(lhs)?;
                let right = self.emit_lir_expression(rhs)?;
                let op_str = match op {
                    x_lir::BinaryOp::Add => "+",
                    x_lir::BinaryOp::Subtract => "-",
                    x_lir::BinaryOp::Multiply => "*",
                    x_lir::BinaryOp::Divide => "/",
                    x_lir::BinaryOp::Modulo => "%",
                    x_lir::BinaryOp::LeftShift => "<<",
                    x_lir::BinaryOp::RightShift => ">>",
                    x_lir::BinaryOp::LessThan => "<",
                    x_lir::BinaryOp::LessThanEqual => "<=",
                    x_lir::BinaryOp::GreaterThan => ">",
                    x_lir::BinaryOp::GreaterThanEqual => ">=",
                    x_lir::BinaryOp::Equal => "==",
                    x_lir::BinaryOp::NotEqual => "!=",
                    x_lir::BinaryOp::BitAnd => "&",
                    x_lir::BinaryOp::BitXor => "^",
                    x_lir::BinaryOp::BitOr => "|",
                    x_lir::BinaryOp::LogicalAnd => "&&",
                    x_lir::BinaryOp::LogicalOr => "||",
                };
                Ok(format!("({} {} {})", left, op_str, right))
            }
            x_lir::Expression::Call(func, args) => {
                // Handle builtin functions
                if let x_lir::Expression::Variable(func_name) = func.as_ref() {
                    match func_name.as_str() {
                        "println" => {
                            self.needs_stdio = true;
                            if args.is_empty() {
                                return Ok("printf(\"\\n\")".to_string());
                            }
                            let arg = self.emit_lir_expression(&args[0])?;
                            // println expects string argument, so use %s by default
                            // Only use %d for integer literals
                            let fmt = if matches!(&args[0], x_lir::Expression::Literal(x_lir::Literal::Integer(_))) {
                                "%d\\n"
                            } else {
                                "%s\\n"
                            };
                            return Ok(format!("printf(\"{}\", {})", fmt, arg));
                        }
                        "print" | "print_inline" => {
                            self.needs_stdio = true;
                            if args.is_empty() {
                                return Ok("printf(\"\")".to_string());
                            }
                            let arg = self.emit_lir_expression(&args[0])?;
                            // Similar logic as println
                            let fmt = if matches!(&args[0], x_lir::Expression::Literal(x_lir::Literal::Integer(_))) {
                                "%d"
                            } else {
                                "%s"
                            };
                            return Ok(format!("printf(\"{}\", {})", fmt, arg));
                        }
                        "exit" => {
                            self.needs_stdlib = true;
                            let args_str: Vec<String> = args
                                .iter()
                                .map(|a| self.emit_lir_expression(a))
                                .collect::<CResult<Vec<_>>>()?;
                            return Ok(format!("exit({})", args_str.join(", ")));
                        }
                        _ => {}
                    }
                }

                let func_str = self.emit_lir_expression(func)?;
                let args_str: Vec<String> = args
                    .iter()
                    .map(|a| self.emit_lir_expression(a))
                    .collect::<CResult<Vec<_>>>()?;
                Ok(format!("{}({})", func_str, args_str.join(", ")))
            }
            x_lir::Expression::Assign(target, value) => {
                let target_str = self.emit_lir_expression(target)?;
                let value_str = self.emit_lir_expression(value)?;
                // For void function calls, just return the call
                if matches!(value.as_ref(), x_lir::Expression::Call(_, _)) {
                    // Check if it's a known void function
                    if let x_lir::Expression::Variable(func_name) = target.as_ref() {
                        // Temporary variables assigned from void functions should just be the call
                        if target_str.starts_with('t') && target_str[1..].parse::<usize>().is_ok() {
                            return Ok(value_str);
                        }
                    }
                    // Check if target is a temp variable (t0, t1, etc.) and value is a call
                    if let x_lir::Expression::Call(_, _) = value.as_ref() {
                        if target_str.starts_with('t') && target_str[1..].parse::<usize>().is_ok() {
                            // This is likely a void function call - just return the call
                            return Ok(value_str);
                        }
                    }
                }
                Ok(format!("{} = {}", target_str, value_str))
            }
            x_lir::Expression::Member(obj, field) => {
                let obj_str = self.emit_lir_expression(obj)?;
                Ok(format!("{}.{}", obj_str, field))
            }
            x_lir::Expression::PointerMember(obj, field) => {
                let obj_str = self.emit_lir_expression(obj)?;
                Ok(format!("{}->{}", obj_str, field))
            }
            x_lir::Expression::Index(arr, idx) => {
                let arr_str = self.emit_lir_expression(arr)?;
                let idx_str = self.emit_lir_expression(idx)?;
                Ok(format!("{}[{}]", arr_str, idx_str))
            }
            x_lir::Expression::AddressOf(e) => {
                Ok(format!("&{}", self.emit_lir_expression(e)?))
            }
            x_lir::Expression::Dereference(e) => {
                Ok(format!("*{}", self.emit_lir_expression(e)?))
            }
            x_lir::Expression::Cast(ty, e) => {
                Ok(format!("(({}){})", self.emit_lir_type(ty), self.emit_lir_expression(e)?))
            }
            x_lir::Expression::Ternary(cond, then_expr, else_expr) => {
                Ok(format!(
                    "({} ? {} : {})",
                    self.emit_lir_expression(cond)?,
                    self.emit_lir_expression(then_expr)?,
                    self.emit_lir_expression(else_expr)?
                ))
            }
            x_lir::Expression::SizeOf(ty) => {
                Ok(format!("sizeof({})", self.emit_lir_type(ty)))
            }
            _ => Ok(format!("/* unsupported expression: {} */", expr)),
        }
    }

    /// Emit LIR literal
    fn emit_lir_literal(&mut self, lit: &x_lir::Literal) -> CResult<String> {
        match lit {
            x_lir::Literal::Integer(n) => Ok(n.to_string()),
            x_lir::Literal::UnsignedInteger(n) => Ok(format!("{}u", n)),
            x_lir::Literal::Long(n) => Ok(format!("{}L", n)),
            x_lir::Literal::UnsignedLong(n) => Ok(format!("{}uL", n)),
            x_lir::Literal::LongLong(n) => Ok(format!("{}LL", n)),
            x_lir::Literal::UnsignedLongLong(n) => Ok(format!("{}uLL", n)),
            x_lir::Literal::Float(n) => Ok(format!("{}f", n)),
            x_lir::Literal::Double(n) => Ok(n.to_string()),
            x_lir::Literal::Char(c) => Ok(format!("'{}'", c)),
            x_lir::Literal::String(s) => {
                let escaped = s
                    .replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('\n', "\\n")
                    .replace('\r', "\\r")
                    .replace('\t', "\\t");
                Ok(format!("\"{}\"", escaped))
            }
            x_lir::Literal::Bool(b) => {
                self.needs_stdbool = true;
                Ok(b.to_string())
            }
            x_lir::Literal::NullPointer => Ok("NULL".to_string()),
        }
    }

    /// Emit LIR type
    fn emit_lir_type(&mut self, ty: &x_lir::Type) -> String {
        match ty {
            x_lir::Type::Void => "void".to_string(),
            x_lir::Type::Bool => {
                self.needs_stdbool = true;
                "bool".to_string()
            }
            x_lir::Type::Char => "char".to_string(),
            x_lir::Type::Schar => "signed char".to_string(),
            x_lir::Type::Uchar => "unsigned char".to_string(),
            x_lir::Type::Short => "short".to_string(),
            x_lir::Type::Ushort => "unsigned short".to_string(),
            x_lir::Type::Int => "int".to_string(),
            x_lir::Type::Uint => "unsigned int".to_string(),
            x_lir::Type::Long => "long".to_string(),
            x_lir::Type::Ulong => "unsigned long".to_string(),
            x_lir::Type::LongLong => "long long".to_string(),
            x_lir::Type::UlongLong => "unsigned long long".to_string(),
            x_lir::Type::Float => "float".to_string(),
            x_lir::Type::Double => "double".to_string(),
            x_lir::Type::LongDouble => "long double".to_string(),
            x_lir::Type::Size => {
                self.needs_stddef = true;
                "size_t".to_string()
            }
            x_lir::Type::Ptrdiff => {
                self.needs_stddef = true;
                "ptrdiff_t".to_string()
            }
            x_lir::Type::Intptr => {
                self.needs_stdint = true;
                "intptr_t".to_string()
            }
            x_lir::Type::Uintptr => {
                self.needs_stdint = true;
                "uintptr_t".to_string()
            }
            x_lir::Type::Pointer(inner) => {
                format!("{}*", self.emit_lir_type(inner))
            }
            x_lir::Type::Array(inner, size) => {
                if let Some(s) = size {
                    format!("{}[{}]", self.emit_lir_type(inner), s)
                } else {
                    format!("{}[]", self.emit_lir_type(inner))
                }
            }
            x_lir::Type::Named(name) => name.clone(),
            x_lir::Type::Qualified(q, inner) => {
                let mut result = String::new();
                if q.is_const {
                    result.push_str("const ");
                }
                if q.is_volatile {
                    result.push_str("volatile ");
                }
                result.push_str(&self.emit_lir_type(inner));
                result
            }
            x_lir::Type::FunctionPointer(_ret, _params) => {
                // Simplified function pointer type
                "void*".to_string()
            }
        }
    }

    /// Emit LIR global variable
    fn emit_lir_global(&mut self, g: &x_lir::GlobalVar) -> CResult<()> {
        let ty = self.emit_lir_type(&g.type_);
        let init = if let Some(init_expr) = &g.initializer {
            format!(" = {}", self.emit_lir_expression(init_expr)?)
        } else {
            String::new()
        };
        let kw = if g.is_static { "static " } else { "" };
        self.line(&format!("{}{} {}{};", kw, ty, g.name, init))?;
        Ok(())
    }

    /// Emit LIR struct
    fn emit_lir_struct(&mut self, s: &x_lir::Struct) -> CResult<()> {
        self.line(&format!("struct {} {{", s.name))?;
        self.indent += 1;
        for field in &s.fields {
            let ty = self.emit_lir_type(&field.type_);
            self.line(&format!("{} {};", ty, field.name))?;
        }
        self.indent -= 1;
        self.line("};")?;
        Ok(())
    }

    /// Emit LIR class (as struct in C)
    fn emit_lir_class(&mut self, c: &x_lir::Class) -> CResult<()> {
        self.line(&format!("/* class {} */", c.name))?;
        self.line(&format!("struct {} {{", c.name))?;
        self.indent += 1;
        for field in &c.fields {
            let ty = self.emit_lir_type(&field.type_);
            self.line(&format!("{} {};", ty, field.name))?;
        }
        self.indent -= 1;
        self.line("};")?;
        Ok(())
    }

    /// Emit LIR vtable
    fn emit_lir_vtable(&mut self, v: &x_lir::VTable) -> CResult<()> {
        self.line(&format!("/* vtable {} for {} */", v.name, v.class_name))?;
        Ok(())
    }

    /// Emit LIR enum
    fn emit_lir_enum(&mut self, e: &x_lir::Enum) -> CResult<()> {
        self.line(&format!("enum {} {{", e.name))?;
        self.indent += 1;
        for (i, variant) in e.variants.iter().enumerate() {
            if let Some(val) = variant.value {
                self.line(&format!("{} = {},", variant.name, val))?;
            } else {
                self.line(&format!("{} = {},", variant.name, i))?;
            }
        }
        self.indent -= 1;
        self.line("};")?;
        Ok(())
    }

    /// Emit LIR type alias
    fn emit_lir_type_alias(&mut self, t: &x_lir::TypeAlias) -> CResult<()> {
        let ty = self.emit_lir_type(&t.type_);
        self.line(&format!("typedef {} {};", ty, t.name))?;
        Ok(())
    }

    /// Emit LIR extern function
    fn emit_lir_extern_function(&mut self, e: &x_lir::ExternFunction) -> CResult<()> {
        // Skip builtin functions that we handle specially
        match e.name.as_str() {
            "println" | "print" | "print_inline" => {
                // These are converted to printf calls, don't emit declarations
                return Ok(());
            }
            "exit" => {
                // exit is handled specially
                return Ok(());
            }
            _ => {}
        }

        let return_type = self.emit_lir_type(&e.return_type);

        // Special handling for printf (variadic function)
        if e.name == "printf" {
            self.line("extern int printf(const char*, ...);")?;
            return Ok(());
        }

        let params = if e.parameters.is_empty() {
            "void".to_string()
        } else {
            e.parameters
                .iter()
                .map(|p| self.emit_lir_type(p))
                .collect::<Vec<_>>()
                .join(", ")
        };
        self.line(&format!("extern {} {}({});", return_type, e.name, params))?;
        Ok(())
    }

    /// Compile generated C code to executable using system C compiler
    pub fn compile_c_code(
        &self,
        c_code: &str,
        output_path: &std::path::Path,
        c_standard: CStandard,
        optimize: bool,
        debug_info: bool,
    ) -> Result<(), CBackendError> {
        use std::process::Command;

        // Write the C code to a temporary file
        let c_file = if output_path.extension().is_some() {
            output_path.with_extension("c")
        } else {
            std::path::PathBuf::from(format!("{}.c", output_path.to_string_lossy()))
        };

        std::fs::write(&c_file, c_code)?;

        // Try to find a C compiler
        let compiler_candidates = ["cc", "gcc", "clang"];
        let mut compiler_path = None;

        for candidate in &compiler_candidates {
            if Command::new(candidate).arg("--version").output().is_ok() {
                compiler_path = Some(*candidate);
                break;
            }
        }

        let compiler = compiler_path.ok_or_else(|| {
            CBackendError::GenerationError(
                "No C compiler found. Please install gcc or clang and add it to PATH.".to_string()
            )
        })?;

        let mut cmd = Command::new(compiler);
        cmd.arg(c_standard.flag());

        if optimize {
            cmd.arg("-O3");
        } else {
            cmd.arg("-O0");
        }

        if debug_info {
            cmd.arg("-g");
        }

        cmd.arg("-o").arg(output_path);
        cmd.arg(&c_file);

        let output = cmd.output().map_err(|e| {
            CBackendError::GenerationError(format!(
                "Failed to execute C compiler: {}",
                e
            ))
        })?;

        if !output.status.success() {
            let error_msg = String::from_utf8_lossy(&output.stderr);
            return Err(CBackendError::GenerationError(format!(
                "C compiler failed with error:\n{}",
                error_msg
            )));
        }

        // Clean up the temporary C file if we're not keeping it
        // We leave it for debugging purposes
        if std::env::var("X_KEEP_C_FILE").is_err() {
            let _ = std::fs::remove_file(&c_file);
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_c_standard_flags() {
        assert_eq!(CStandard::C99.flag(), "-std=c99");
        assert_eq!(CStandard::C11.flag(), "-std=c11");
        assert_eq!(CStandard::C23.flag(), "-std=c23");
    }

    #[test]
    fn test_default_config() {
        let config = CBackendConfig::default();
        assert_eq!(config.c_standard, CStandard::C23);
        assert!(!config.optimize);
        assert!(config.debug_info);
    }

    #[test]
    fn test_empty_program() {
        let mut backend = CBackend::new(CBackendConfig::default());
        // 使用 x_parser 解析空程序
        let program = x_parser::parse_program("").unwrap();
        let output = backend.generate_from_ast(&program).unwrap();
        assert_eq!(output.files.len(), 1);
        let content = String::from_utf8_lossy(&output.files[0].content);
        assert!(content.contains("int main(void)"));
    }

    #[test]
    fn test_type_mapping() {
        let mut backend = CBackend::new(CBackendConfig::default());

        assert_eq!(backend.emit_type(&x_parser::ast::Type::Bool), "bool");
        assert!(backend.needs_stdbool);

        assert_eq!(backend.emit_type(&x_parser::ast::Type::Int), "int32_t");
        assert!(backend.needs_stdint);

        assert_eq!(backend.emit_type(&x_parser::ast::Type::Float), "double");
    }
}
