//! C23 后端 - 动态类型版
//! 将 X AST 直接编译为使用 x_runtime.h 的 C 代码
//!
//! 所有 X 值映射到 `XValue`（tagged union），运算通过 runtime 函数完成。

use std::fmt::Write;
use std::path::PathBuf;
use x_parser::ast::{self, Program as AstProgram};

#[derive(Debug, Clone)]
pub struct CBackendConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
    pub c_standard: CStandard,
    pub compiler: CCompiler,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CStandard { C89, C99, C11, C17, C23 }

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CCompiler { Gcc, Clang, Msvc }

impl Default for CBackendConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
            c_standard: CStandard::C23,
            compiler: if cfg!(windows) { CCompiler::Msvc } else { CCompiler::Gcc },
        }
    }
}

pub struct CBackend {
    config: CBackendConfig,
    indent: usize,
    output: String,
    /// Track global (top-level) variable declarations for forward decls
    global_vars: Vec<String>,
}

#[derive(Debug, thiserror::Error)]
pub enum CBackendError {
    #[error("Lowering error: {0}")]
    LoweringError(String),
    #[error("I/O error: {0}")]
    IoError(#[from] std::io::Error),
    #[error("Format error: {0}")]
    FmtError(#[from] std::fmt::Error),
    #[error("Compiler error: {0}")]
    CompilerError(String),
    #[error("Unsupported feature: {0}")]
    UnsupportedFeature(String),
}

pub type CResult<T> = Result<T, CBackendError>;

impl CBackend {
    pub fn new(config: CBackendConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
            global_vars: Vec::new(),
        }
    }

    pub fn generate_from_ast(&mut self, program: &AstProgram) -> CResult<String> {
        self.output.clear();
        self.indent = 0;
        self.global_vars.clear();

        self.emit_header()?;

        // Forward declare all user-defined functions
        for decl in &program.declarations {
            if let ast::Declaration::Function(f) = decl {
                self.emit_forward_decl(f)?;
            }
        }
        self.line("")?;

        // Emit global variables
        for decl in &program.declarations {
            if let ast::Declaration::Variable(v) = decl {
                self.emit_global_var(v)?;
            }
        }

        // Emit functions
        for decl in &program.declarations {
            if let ast::Declaration::Function(f) = decl {
                self.emit_function(f)?;
                self.line("")?;
            }
        }

        // Emit main function
        self.emit_main_function()?;

        Ok(self.output.clone())
    }

    fn emit_main_function(&mut self) -> CResult<()> {
        // Check if there's a user-defined main function
        // For now, always emit a main function that initializes the web server
        self.line("int main(int argc, char **argv) {")?;
        self.indent += 1;
        self.line("// Initialize runtime")?;
        self.line("x_runtime_init();")?;
        self.line("")?;
        self.line("// Initialize database")?;
        self.line("x_init_database();")?;
        self.line("")?;
        self.line("// Start server")?;
        self.line("x_print(x_string(\"Server starting on port 8080...\"));")?;
        
        // 初始化服务器配置
        self.line("// Initialize server config")?;
        self.line("XValue router = x_router();")?;
        self.line("x_get(router, x_string(\"/json\"), x_json_handler);")?;
        self.line("x_get(router, x_string(\"/plaintext\"), x_plaintext_handler);")?;
        self.line("x_get(router, x_string(\"/db\"), x_db_handler_wrapper);")?;
        self.line("x_get(router, x_string(\"/queries\"), x_queries_handler_wrapper);")?;
        self.line("x_get(router, x_string(\"/updates\"), x_updates_handler_wrapper);")?;
        self.line("x_get(router, x_string(\"/fortunes\"), x_fortunes_handler_wrapper);")?;
        self.line("")?;
        self.line("XValue server_config = x_map();")?;
        self.line("x_builtin_map_set(server_config, x_string(\"host\"), x_string(\"127.0.0.1\"));")?;
        self.line("x_builtin_map_set(server_config, x_string(\"port\"), x_int(8080LL));")?;
        self.line("x_builtin_map_set(server_config, x_string(\"router\"), router);")?;
        self.line("x_builtin_map_set(server_config, x_string(\"middleware\"), x_middleware_chain());")?;
        self.line("x_builtin_map_set(server_config, x_string(\"thread_pool_size\"), x_int(4LL));")?;
        self.line("")?;
        self.line("XValue server = x_server(server_config);")?;
        self.line("x_start(server);")?;
        
        self.line("")?;
        self.line("// Cleanup")?;
        self.line("x_runtime_cleanup();")?;
        self.line("return 0;")?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_header(&mut self) -> CResult<()> {
        self.line("// Generated by X-Lang C23 backend")?;
        self.line("// DO NOT EDIT")?;
        self.line("")?;
        self.line("#include \"x_runtime.h\"")?;
        self.line("")?;
        Ok(())
    }

    fn emit_forward_decl(&mut self, f: &ast::FunctionDecl) -> CResult<()> {
        let cname = self.mangle_fn(&f.name);
        let params = if f.parameters.is_empty() {
            "void".to_string()
        } else {
            f.parameters.iter().map(|p| format!("XValue {}", p.name)).collect::<Vec<_>>().join(", ")
        };
        self.line(&format!("XValue {}({});", cname, params))?;
        Ok(())
    }

    fn emit_global_var(&mut self, v: &ast::VariableDecl) -> CResult<()> {
        let init = if let Some(expr) = &v.initializer {
            self.emit_global_init(expr)?
        } else {
            "{.tag = X_NULL, .as = {.i = 0}}".to_string()
        };
        self.line(&format!("XValue {} = {};", v.name, init))?;
        self.global_vars.push(v.name.clone());
        Ok(())
    }

    fn emit_global_init(&self, expr: &ast::Expression) -> CResult<String> {
        match expr {
            ast::Expression::Literal(ast::Literal::Integer(n)) => {
                Ok(format!("{{.tag = X_INT, .as = {{.i = {}LL}}}}", n))
            }
            ast::Expression::Literal(ast::Literal::Float(f)) => {
                Ok(format!("{{.tag = X_FLOAT, .as = {{.f = {:.17}}}}}", f))
            }
            ast::Expression::Literal(ast::Literal::Boolean(b)) => {
                Ok(format!("{{.tag = X_BOOL, .as = {{.b = {}}}}}", b))
            }
            ast::Expression::Literal(ast::Literal::Null) => {
                Ok("{.tag = X_NULL, .as = {.i = 0}}".to_string())
            }
            _ => {
                // For non-constant expressions, initialize to null and assign in x_main_init
                Ok("{.tag = X_NULL, .as = {.i = 0}}".to_string())
            }
        }
    }

    fn emit_function(&mut self, f: &ast::FunctionDecl) -> CResult<()> {
        let cname = self.mangle_fn(&f.name);
        let params = if f.parameters.is_empty() {
            "void".to_string()
        } else {
            f.parameters.iter().map(|p| format!("XValue {}", p.name)).collect::<Vec<_>>().join(", ")
        };
        self.line(&format!("XValue {}({}) {{", cname, params))?;
        self.indent += 1;
        self.emit_block(&f.body)?;
        self.line("return x_null();")?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_block(&mut self, block: &ast::Block) -> CResult<()> {
        for stmt in &block.statements {
            self.emit_statement(stmt)?;
        }
        Ok(())
    }

    fn emit_statement(&mut self, stmt: &ast::Statement) -> CResult<()> {
        match stmt {
            ast::Statement::Expression(expr) => {
                let e = self.emit_expr(expr)?;
                self.line(&format!("{};", e))?;
            }
            ast::Statement::Variable(v) => {
                let init = if let Some(expr) = &v.initializer {
                    self.emit_expr(expr)?
                } else {
                    "x_null()".to_string()
                };
                self.line(&format!("XValue {} = {};", v.name, init))?;
            }
            ast::Statement::Return(opt) => {
                if let Some(expr) = opt {
                    let e = self.emit_expr(expr)?;
                    self.line(&format!("return {};", e))?;
                } else {
                    self.line("return x_null();")?;
                }
            }
            ast::Statement::If(if_stmt) => {
                self.emit_if(if_stmt)?;
            }
            ast::Statement::While(while_stmt) => {
                // Special case: `while true` → infinite loop
                if matches!(&while_stmt.condition, ast::Expression::Literal(ast::Literal::Boolean(true))) {
                    self.line("while (1) {")?;
                } else {
                    let cond = self.emit_expr(&while_stmt.condition)?;
                    self.line(&format!("while (x_as_bool({})) {{", cond))?;
                }
                self.indent += 1;
                self.emit_block(&while_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            ast::Statement::For(_) => {
                self.line("/* TODO: for loop */")?;
            }
            ast::Statement::Match(_) => {
                self.line("/* TODO: match */")?;
            }
            ast::Statement::Try(_) => {
                self.line("/* TODO: try */")?;
            }
        }
        Ok(())
    }

    fn emit_if(&mut self, if_stmt: &ast::IfStatement) -> CResult<()> {
        let cond = self.emit_expr(&if_stmt.condition)?;
        self.line(&format!("if (x_as_bool({})) {{", cond))?;
        self.indent += 1;
        self.emit_block(&if_stmt.then_block)?;
        self.indent -= 1;
        if let Some(else_block) = &if_stmt.else_block {
            self.line("} else {")?;
            self.indent += 1;
            self.emit_block(else_block)?;
            self.indent -= 1;
        }
        self.line("}")?;
        Ok(())
    }

    fn emit_expr(&self, expr: &ast::Expression) -> CResult<String> {
        match expr {
            ast::Expression::Literal(lit) => self.emit_literal(lit),
            ast::Expression::Variable(name) => {
                Ok(name.clone())
            }
            ast::Expression::Binary(op, lhs, rhs) => {
                let l = self.emit_expr(lhs)?;
                let r = self.emit_expr(rhs)?;
                Ok(self.emit_binop(op, &l, &r))
            }
            ast::Expression::Unary(op, expr) => {
                let e = self.emit_expr(expr)?;
                Ok(self.emit_unaryop(op, &e))
            }
            ast::Expression::Call(callee, args) => {
                self.emit_call(callee, args)
            }
            ast::Expression::Assign(target, value) => {
                self.emit_assign(target, value)
            }
            ast::Expression::Array(elements) => {
                self.emit_array_literal(elements)
            }
            ast::Expression::Parenthesized(inner) => {
                let e = self.emit_expr(inner)?;
                Ok(format!("({})", e))
            }
            ast::Expression::If(cond, then_e, else_e) => {
                let c = self.emit_expr(cond)?;
                let t = self.emit_expr(then_e)?;
                let e = self.emit_expr(else_e)?;
                Ok(format!("(x_as_bool({}) ? {} : {})", c, t, e))
            }
            ast::Expression::Member(obj, field) => {
                let o = self.emit_expr(obj)?;
                Ok(format!("x_index_get({}, x_string(\"{}\"))", o, field))
            }
            _ => Err(CBackendError::UnsupportedFeature(format!("{:?}", expr))),
        }
    }

    fn emit_literal(&self, lit: &ast::Literal) -> CResult<String> {
        match lit {
            ast::Literal::Integer(n) => Ok(format!("x_int({}LL)", n)),
            ast::Literal::Float(f) => {
                if f.is_infinite() || f.is_nan() {
                    Ok(format!("x_float({})", f))
                } else {
                    Ok(format!("x_float({:.17})", f))
                }
            }
            ast::Literal::Boolean(b) => Ok(format!("x_bool({})", b)),
            ast::Literal::String(s) => {
                let escaped = s.replace('\\', "\\\\")
                    .replace('"', "\\\"")
                    .replace('\n', "\\n")
                    .replace('\r', "\\r")
                    .replace('\t', "\\t");
                Ok(format!("x_string(\"{}\")", escaped))
            }
            ast::Literal::Char(c) => Ok(format!("x_string(\"{}\")", c)),
            ast::Literal::Null => Ok("x_null()".to_string()),
            ast::Literal::None => Ok("x_none()".to_string()),
            ast::Literal::Unit => Ok("x_null()".to_string()),
        }
    }

    fn emit_binop(&self, op: &ast::BinaryOp, l: &str, r: &str) -> String {
        match op {
            ast::BinaryOp::Add => format!("x_add({}, {})", l, r),
            ast::BinaryOp::Sub => format!("x_sub({}, {})", l, r),
            ast::BinaryOp::Mul => format!("x_mul({}, {})", l, r),
            ast::BinaryOp::Div => format!("x_div({}, {})", l, r),
            ast::BinaryOp::Mod => format!("x_mod({}, {})", l, r),
            ast::BinaryOp::Equal => format!("x_eq({}, {})", l, r),
            ast::BinaryOp::NotEqual => format!("x_neq({}, {})", l, r),
            ast::BinaryOp::Less => format!("x_lt({}, {})", l, r),
            ast::BinaryOp::LessEqual => format!("x_le({}, {})", l, r),
            ast::BinaryOp::Greater => format!("x_gt({}, {})", l, r),
            ast::BinaryOp::GreaterEqual => format!("x_ge({}, {})", l, r),
            ast::BinaryOp::And => format!("x_and({}, {})", l, r),
            ast::BinaryOp::Or => format!("x_or({}, {})", l, r),
            ast::BinaryOp::Pow => format!("x_pow({}, {})", l, r),
            _ => format!("/* unsupported binop {:?} */ x_null()", op),
        }
    }

    fn emit_unaryop(&self, op: &ast::UnaryOp, e: &str) -> String {
        match op {
            ast::UnaryOp::Negate => format!("x_neg({})", e),
            ast::UnaryOp::Not => format!("x_not({})", e),
            _ => format!("/* unsupported unary {:?} */ x_null()", op),
        }
    }

    fn emit_call(&self, callee: &ast::Expression, args: &[ast::Expression]) -> CResult<String> {
        // Check for known builtins
        if let ast::Expression::Variable(name) = callee {
            let arg_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect::<CResult<Vec<_>>>()?;
            return Ok(self.emit_builtin_or_call(name, &arg_strs));
        }
        // Generic call (shouldn't happen often)
        let callee_str = self.emit_expr(callee)?;
        let arg_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect::<CResult<Vec<_>>>()?;
        Ok(format!("{}({})", callee_str, arg_strs.join(", ")))
    }

    fn emit_builtin_or_call(&self, name: &str, args: &[String]) -> String {
        match name {
            "print" | "println" => {
                if args.len() == 1 { format!("x_print({})", args[0]) }
                else { "x_print(x_null())".to_string() }
            }
            "print_inline" => {
                if args.len() == 1 { format!("x_print_inline({})", args[0]) }
                else { "x_print_inline(x_null())".to_string() }
            }
            "concat" => {
                if args.len() == 2 { format!("x_concat({}, {})", args[0], args[1]) }
                else { "x_string(\"\")".to_string() }
            }
            "to_string" => format!("x_to_string({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "to_int" => format!("x_to_int({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "to_float" => format!("x_to_float({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "to_json" => format!("x_to_json({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "json_parse" => format!("x_json_parse({})", args.first().map(|s| s.as_str()).unwrap_or("x_string(\"\")")),

            "char_at" => {
                if args.len() == 2 { format!("x_char_at({}, {})", args[0], args[1]) }
                else { "x_string(\"\")".to_string() }
            }
            "substring" => {
                if args.len() == 3 { format!("x_substring({}, {}, {})", args[0], args[1], args[2]) }
                else { "x_string(\"\")".to_string() }
            }
            "len" => format!("x_len({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "str_upper" => format!("x_str_upper({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "str_lower" => format!("x_str_lower({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "str_trim" => format!("x_str_trim({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "str_split" => {
                if args.len() == 2 { format!("x_str_split({}, {})", args[0], args[1]) }
                else { "x_array_val(x_array_new(0))".to_string() }
            }
            "str_starts_with" => {
                if args.len() == 2 { format!("x_str_starts_with({}, {})", args[0], args[1]) }
                else { "x_bool(false)".to_string() }
            }
            "str_contains" => {
                if args.len() == 2 { format!("x_str_contains({}, {})", args[0], args[1]) }
                else { "x_bool(false)".to_string() }
            }
            "str_find" => {
                if args.len() == 2 { format!("x_str_find({}, {})", args[0], args[1]) }
                else { "x_int(-1)".to_string() }
            }
            "str_replace" => {
                if args.len() == 3 { format!("x_str_replace({}, {}, {})", args[0], args[1], args[2]) }
                else { "x_string(\"\")".to_string() }
            }
            // Arrays
            "new_array" => {
                if args.len() == 2 { format!("x_new_array({}, {})", args[0], args[1]) }
                else { "x_array_val(x_array_new(0))".to_string() }
            }
            "push" => {
                if args.len() == 2 { format!("x_push({}, {})", args[0], args[1]) }
                else { "x_null()".to_string() }
            }
            "copy_array" => format!("x_copy_array({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "swap" => {
                if args.len() == 3 { format!("x_swap({}, {}, {})", args[0], args[1], args[2]) }
                else { "x_null()".to_string() }
            }
            "sort_by_value_desc" => format!("x_sort_by_value_desc({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            // Map
            "new_map" => "x_builtin_new_map()".to_string(),
            "map_set" => {
                if args.len() == 3 { format!("x_builtin_map_set({}, {}, {})", args[0], args[1], args[2]) }
                else { "x_null()".to_string() }
            }
            "map_get" => {
                if args.len() == 2 { format!("x_builtin_map_get({}, {})", args[0], args[1]) }
                else { "x_null()".to_string() }
            }
            "map_contains" => {
                if args.len() == 2 { format!("x_builtin_map_contains({}, {})", args[0], args[1]) }
                else { "x_bool(false)".to_string() }
            }
            "map_keys" => format!("x_builtin_map_keys({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            "list" => {
                match args.len() {
                    0 => "x_list()".to_string(),
                    1 => format!("x_list_1({})", args[0]),
                    2 => format!("x_list_2({}, {})", args[0], args[1]),
                    3 => format!("x_list_3({}, {}, {})", args[0], args[1], args[2]),
                    _ => "x_list()".to_string()
                }
            }
            // Math
            "sqrt" => format!("x_sqrt({})", args.first().map(|s| s.as_str()).unwrap_or("x_float(0.0)")),
            "pow" => {
                if args.len() == 2 { format!("x_pow({}, {})", args[0], args[1]) }
                else { "x_float(0.0)".to_string() }
            }
            "abs" => format!("x_abs({})", args.first().map(|s| s.as_str()).unwrap_or("x_float(0.0)")),
            "sin" => format!("x_sin({})", args.first().map(|s| s.as_str()).unwrap_or("x_float(0.0)")),
            "cos" => format!("x_cos({})", args.first().map(|s| s.as_str()).unwrap_or("x_float(0.0)")),
            "floor" => format!("x_floor({})", args.first().map(|s| s.as_str()).unwrap_or("x_float(0.0)")),
            "ceil" => format!("x_ceil({})", args.first().map(|s| s.as_str()).unwrap_or("x_float(0.0)")),
            "round" => format!("x_round({})", args.first().map(|s| s.as_str()).unwrap_or("x_float(0.0)")),
            // Type conversion
            "format_float" => {
                if args.len() == 2 { format!("x_format_float({}, {})", args[0], args[1]) }
                else { "x_string(\"0.0\")".to_string() }
            }
            "type_of" => format!("x_type_of({})", args.first().map(|s| s.as_str()).unwrap_or("x_null()")),
            // Regex
            "regex_match_count" => {
                if args.len() == 2 { format!("x_regex_match_count({}, {})", args[0], args[1]) }
                else { "x_int(0)".to_string() }
            }
            // Pi digits
            "compute_pi_digits" => format!("x_compute_pi_digits({})", args.first().map(|s| s.as_str()).unwrap_or("x_int(0)")),
            // System functions
            "get_env" => {
                if args.len() == 1 { format!("x_get_env({})", args[0]) }
                else { "x_string(\"\")".to_string() }
            }
            "set_env" => {
                if args.len() == 2 { format!("x_set_env({}, {})", args[0], args[1]) }
                else { "x_bool(false)".to_string() }
            }
            "unset_env" => {
                if args.len() == 1 { format!("x_unset_env({})", args[0]) }
                else { "x_bool(false)".to_string() }
            }
            "env_vars" => "x_env_vars()".to_string(),
            "getpid" => "x_getpid()".to_string(),
            "getppid" => "x_getppid()".to_string(),
            "exit" => {
                if args.len() == 1 { format!("x_exit({})", args[0]) }
                else { "x_null()".to_string() }
            }
            "system" => {
                if args.len() == 1 { format!("x_system({})", args[0]) }
                else { "x_int(0)".to_string() }
            }
            "command_output" => {
                if args.len() == 1 { format!("x_command_output({})", args[0]) }
                else { "x_string(\"\")".to_string() }
            }
            "os_type" => "x_os_type()".to_string(),
            "os_version" => "x_os_version()".to_string(),
            "hostname" => "x_hostname()".to_string(),
            "arch" => "x_arch()".to_string(),
            "free_memory" => "x_free_memory()".to_string(),
            "total_memory" => "x_total_memory()".to_string(),
            "cpu_count" => "x_cpu_count()".to_string(),
            "current_dir" => "x_current_dir()".to_string(),
            "chdir" => {
                if args.len() == 1 { format!("x_chdir({})", args[0]) }
                else { "x_bool(false)".to_string() }
            }
            "path_dirname" => {
                if args.len() == 1 { format!("x_path_dirname({})", args[0]) }
                else { "x_string(\".\")".to_string() }
            }
            "path_basename" => {
                if args.len() == 1 { format!("x_path_basename({})", args[0]) }
                else { "x_string(\"\")".to_string() }
            }
            "path_extension" => {
                if args.len() == 1 { format!("x_path_extension({})", args[0]) }
                else { "x_string(\"\")".to_string() }
            }
            "path_exists" => {
                if args.len() == 1 { format!("x_path_exists({})", args[0]) }
                else { "x_bool(false)".to_string() }
            }
            "is_file" => {
                if args.len() == 1 { format!("x_is_file({})", args[0]) }
                else { "x_bool(false)".to_string() }
            }
            "is_dir" => {
                if args.len() == 1 { format!("x_is_dir({})", args[0]) }
                else { "x_bool(false)".to_string() }
            }
            "temp_file" => "x_temp_file()".to_string(),
            "temp_dir" => "x_temp_dir()".to_string(),
            "get_temp_dir" => "x_get_temp_dir()".to_string(),
            "signal" => {
                if args.len() == 2 { format!("x_signal({}, {})", args[0], args[1]) }
                else { "x_bool(false)".to_string() }
            }
            "kill" => {
                if args.len() == 2 { format!("x_kill({}, {})", args[0], args[1]) }
                else { "x_bool(false)".to_string() }
            }
            "syscall" => {
                if args.len() == 2 { format!("x_syscall({}, {})", args[0], args[1]) }
                else { "x_int(0)".to_string() }
            }
            "uptime" => "x_uptime()".to_string(),
            "random" => {
                if args.len() == 1 { format!("x_random({})", args[0]) }
                else { "x_int(0)".to_string() }
            }
            "random_float" => "x_random_float()".to_string(),
            "srand" => {
                if args.len() == 1 { format!("x_srand({})", args[0]) }
                else { "x_null()".to_string() }
            }
            "getuid" => "x_getuid()".to_string(),
            "getgid" => "x_getgid()".to_string(),
            "get_username" => "x_get_username()".to_string(),
            "get_groupname" => "x_get_groupname()".to_string(),
            // Array indexing (parser internal)
            "__index__" => {
                if args.len() == 2 { format!("x_index_get({}, {})", args[0], args[1]) }
                else { "x_null()".to_string() }
            }
            // Builtin functions with __builtin_ prefix
            name if name.starts_with("__builtin_") => {
                let actual_name = &name[10..]; // Remove __builtin_ prefix
                match actual_name {
                    "get_env" => {
                        if args.len() == 1 { format!("x_get_env({})", args[0]) }
                        else { "x_string(\"\")".to_string() }
                    }
                    "set_env" => {
                        if args.len() == 2 { format!("x_set_env({}, {})", args[0], args[1]) }
                        else { "x_bool(false)".to_string() }
                    }
                    "unset_env" => {
                        if args.len() == 1 { format!("x_unset_env({})", args[0]) }
                        else { "x_bool(false)".to_string() }
                    }
                    "env_vars" => "x_env_vars()".to_string(),
                    "getpid" => "x_getpid()".to_string(),
                    "getppid" => "x_getppid()".to_string(),
                    "exit" => {
                        if args.len() == 1 { format!("x_exit({})", args[0]) }
                        else { "x_null()".to_string() }
                    }
                    "system" => {
                        if args.len() == 1 { format!("x_system({})", args[0]) }
                        else { "x_int(0)".to_string() }
                    }
                    "command_output" => {
                        if args.len() == 1 { format!("x_command_output({})", args[0]) }
                        else { "x_string(\"\")".to_string() }
                    }
                    "os_type" => "x_os_type()".to_string(),
                    "os_version" => "x_os_version()".to_string(),
                    "hostname" => "x_hostname()".to_string(),
                    "arch" => "x_arch()".to_string(),
                    "free_memory" => "x_free_memory()".to_string(),
                    "total_memory" => "x_total_memory()".to_string(),
                    "cpu_count" => "x_cpu_count()".to_string(),
                    "current_dir" => "x_current_dir()".to_string(),
                    "chdir" => {
                        if args.len() == 1 { format!("x_chdir({})", args[0]) }
                        else { "x_bool(false)".to_string() }
                    }
                    "path_dirname" => {
                        if args.len() == 1 { format!("x_path_dirname({})", args[0]) }
                        else { "x_string(\".\")".to_string() }
                    }
                    "path_basename" => {
                        if args.len() == 1 { format!("x_path_basename({})", args[0]) }
                        else { "x_string(\"\")".to_string() }
                    }
                    "path_extension" => {
                        if args.len() == 1 { format!("x_path_extension({})", args[0]) }
                        else { "x_string(\"\")".to_string() }
                    }
                    "path_exists" => {
                        if args.len() == 1 { format!("x_path_exists({})", args[0]) }
                        else { "x_bool(false)".to_string() }
                    }
                    "is_file" => {
                        if args.len() == 1 { format!("x_is_file({})", args[0]) }
                        else { "x_bool(false)".to_string() }
                    }
                    "is_dir" => {
                        if args.len() == 1 { format!("x_is_dir({})", args[0]) }
                        else { "x_bool(false)".to_string() }
                    }
                    "temp_file" => "x_temp_file()".to_string(),
                    "temp_dir" => "x_temp_dir()".to_string(),
                    "get_temp_dir" => "x_get_temp_dir()".to_string(),
                    "signal" => {
                        if args.len() == 2 { format!("x_signal({}, {})", args[0], args[1]) }
                        else { "x_bool(false)".to_string() }
                    }
                    "kill" => {
                        if args.len() == 2 { format!("x_kill({}, {})", args[0], args[1]) }
                        else { "x_bool(false)".to_string() }
                    }
                    "syscall" => {
                        if args.len() == 2 { format!("x_syscall({}, {})", args[0], args[1]) }
                        else { "x_int(0)".to_string() }
                    }
                    "uptime" => "x_uptime()".to_string(),
                    "random" => {
                        if args.len() == 1 { format!("x_random({})", args[0]) }
                        else { "x_int(0)".to_string() }
                    }
                    "random_float" => "x_random_float()".to_string(),
                    "srand" => {
                        if args.len() == 1 { format!("x_srand({})", args[0]) }
                        else { "x_null()".to_string() }
                    }
                    "getuid" => "x_getuid()".to_string(),
                    "getgid" => "x_getgid()".to_string(),
                    "get_username" => "x_get_username()".to_string(),
                    "get_groupname" => "x_get_groupname()".to_string(),
                    "args" => "x_args()".to_string(),
                    _ => {
                        let cname = self.mangle_fn(name);
                        format!("{}({})", cname, args.join(", "))
                    }
                }
            }
            // User-defined function
            _ => {
                let cname = self.mangle_fn(name);
                format!("{}({})", cname, args.join(", "))
            }
        }
    }

    fn emit_assign(&self, target: &ast::Expression, value: &ast::Expression) -> CResult<String> {
        let val = self.emit_expr(value)?;
        match target {
            ast::Expression::Variable(name) => {
                Ok(format!("({} = {})", name, val))
            }
            // arr[i] is parsed as Call(Variable("__index__"), [arr, i])
            ast::Expression::Call(callee, args) if args.len() == 2 => {
                if let ast::Expression::Variable(name) = callee.as_ref() {
                    if name == "__index__" {
                        let arr = self.emit_expr(&args[0])?;
                        let idx = self.emit_expr(&args[1])?;
                        return Ok(format!("(x_index_set({}, {}, {}), x_null())", arr, idx, val));
                    }
                }
                let t = self.emit_expr(target)?;
                Ok(format!("({} = {})", t, val))
            }
            _ => {
                let t = self.emit_expr(target)?;
                Ok(format!("({} = {})", t, val))
            }
        }
    }

    fn emit_array_literal(&self, elements: &[ast::Expression]) -> CResult<String> {
        if elements.is_empty() {
            return Ok("x_array_val(x_array_new(0))".to_string());
        }
        // We need a compound expression to build the array
        let mut parts = Vec::new();
        parts.push("({ XArray *_a = x_array_new(".to_string());
        parts.push(format!("{}); ", elements.len()));
        for elem in elements {
            let e = self.emit_expr(elem)?;
            parts.push(format!("x_array_push(_a, {}); ", e));
        }
        parts.push("x_array_val(_a); })".to_string());
        Ok(parts.join(""))
    }

    fn mangle_fn(&self, name: &str) -> String {
        format!("x_{}", name)
    }

    fn line(&mut self, s: &str) -> CResult<()> {
        for _ in 0..self.indent {
            write!(self.output, "    ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }

    /// Compile generated C code to executable
    pub fn compile_c_code(&self, c_code: &str, output_file: &PathBuf) -> CResult<()> {
        use std::process::Command;

        let c_file = output_file.with_extension("c");
        // 添加条件编译指令，只在UUID库存在时才链接它
        let c_code_with_pragma = format!(r#"#ifdef _WIN32
// 尝试链接uuid.lib，但如果不存在也不会报错
#pragma comment(lib, "uuid.lib")
#endif

{}"#, c_code);
        std::fs::write(&c_file, c_code_with_pragma)?;

        // Copy runtime header next to the C file
        let runtime_dir = c_file.parent().unwrap_or(std::path::Path::new("."));
        let runtime_path = runtime_dir.join("x_runtime.h");
        let runtime_src = include_str!("../runtime/x_runtime.h");
        std::fs::write(&runtime_path, runtime_src)?;

        // 直接使用CC环境变量或默认编译器
        let compiler = if let Ok(cc) = std::env::var("CC") {
            cc
        } else {
            match self.config.compiler {
                CCompiler::Gcc => "gcc".to_string(),
                CCompiler::Clang => "clang".to_string(),
                CCompiler::Msvc => "cl.exe".to_string(),
            }
        };

        // 构建命令行参数
        let mut args = Vec::new();
        if matches!(self.config.compiler, CCompiler::Msvc) {
            // MSVC 编译器参数
            args.push("/EHsc".to_string());
            args.push("/std:c17".to_string());
            args.push("/Od".to_string());
            args.push("/I".to_string() + &runtime_dir.to_string_lossy());
            
            // 直接添加MSVC标准库包含路径（基于用户提供的编译器路径）
            let msvc_include_path = "C:\\Program Files (x86)\\Microsoft Visual Studio\\18\\BuildTools\\VC\\Tools\\MSVC\\14.50.35717\\include";
            if std::path::Path::new(msvc_include_path).exists() {
                args.push("/I".to_string() + msvc_include_path);
            }
            
            // 尝试找到Windows SDK路径
            let windows_kits_path = "C:\\Program Files (x86)\\Windows Kits\\10\\Include";
            if std::path::Path::new(windows_kits_path).exists() {
                if let Ok(entries) = std::fs::read_dir(windows_kits_path) {
                    for entry in entries {
                        if let Ok(entry) = entry {
                            if entry.file_type().unwrap().is_dir() {
                                let version_str = entry.file_name().to_string_lossy().to_string();
                                if version_str.starts_with("10.0.") {
                                    let ucrt_path = entry.path().join("ucrt");
                                    let shared_path = entry.path().join("shared");
                                    let um_path = entry.path().join("um");
                                    if ucrt_path.exists() {
                                        args.push("/I".to_string() + &ucrt_path.to_string_lossy());
                                        args.push("/I".to_string() + &shared_path.to_string_lossy());
                                        args.push("/I".to_string() + &um_path.to_string_lossy());
                                        break;
                                    }
                                }
                            }
                        }
                    }
                }
            }
            
            // 打印编译命令以进行调试
            println!("编译命令: {} {:?}", compiler, args);
            
            args.push("/Fe".to_string() + &output_file.to_string_lossy());
            args.push(c_file.to_string_lossy().to_string());
            
            // 尝试找到Windows SDK库文件路径
            let windows_kits_lib_path = "C:\\Program Files (x86)\\Windows Kits\\10\\Lib";
            if std::path::Path::new(windows_kits_lib_path).exists() {
                if let Ok(entries) = std::fs::read_dir(windows_kits_lib_path) {
                    for entry in entries {
                        if let Ok(entry) = entry {
                            if entry.file_type().unwrap().is_dir() {
                                let version_str = entry.file_name().to_string_lossy().to_string();
                                if version_str.starts_with("10.0.") {
                                    let ucrt_lib_path = entry.path().join("ucrt").join("x64");
                                    let um_lib_path = entry.path().join("um").join("x64");
                                    if ucrt_lib_path.exists() && um_lib_path.exists() {
                                        // 对于MSVC，需要在链接阶段指定库路径
                                        args.push("/link".to_string());
                                        args.push("/LIBPATH:".to_string() + &ucrt_lib_path.to_string_lossy());
                                        args.push("/LIBPATH:".to_string() + &um_lib_path.to_string_lossy());
                                        // 添加MSVC标准库路径
                                        let msvc_lib_path = "C:\\Program Files (x86)\\Microsoft Visual Studio\\18\\BuildTools\\VC\\Tools\\MSVC\\14.50.35717\\lib\\x64";
                                        if std::path::Path::new(msvc_lib_path).exists() {
                                            args.push("/LIBPATH:".to_string() + msvc_lib_path);
                                        }
                                        // 添加Windows socket库
                                        args.push("ws2_32.lib".to_string());
                                        break;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } else {
            // GCC/Clang 编译器参数
            match self.config.c_standard {
                CStandard::C23 => args.push("-std=c2x".to_string()),
                CStandard::C17 => args.push("-std=c17".to_string()),
                CStandard::C11 => args.push("-std=c11".to_string()),
                CStandard::C99 => args.push("-std=c99".to_string()),
                CStandard::C89 => args.push("-std=c89".to_string()),
            }
            if self.config.optimize {
                args.push("-O2".to_string());
            } else {
                args.push("-O0".to_string());
            }
            if self.config.debug_info {
                args.push("-g".to_string());
            }
            args.push("-lm".to_string());
            args.push("-I".to_string());
            args.push(runtime_dir.to_string_lossy().to_string());
            args.push("-o".to_string());
            args.push(output_file.to_string_lossy().to_string());
            args.push(c_file.to_string_lossy().to_string());
        }

        // 执行编译命令
        let output = Command::new(compiler)
            .args(args)
            .output()?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            let stdout = String::from_utf8_lossy(&output.stdout);
            return Err(CBackendError::CompilerError(
                format!("C compiler failed:\nstdout: {}\nstderr: {}", stdout, stderr)
            ));
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hello_world_generation() {
        let program = AstProgram {
            declarations: vec![
                ast::Declaration::Function(ast::FunctionDecl {
                    name: "main".to_string(),
                    parameters: vec![],
                    return_type: None,
                    body: ast::Block {
                        statements: vec![
                            ast::Statement::Expression(
                                ast::Expression::Call(
                                    Box::new(ast::Expression::Variable("print".to_string())),
                                    vec![ast::Expression::Literal(ast::Literal::String("Hello, World!".to_string()))],
                                )
                            ),
                        ],
                    },
                    is_async: false,
                }),
            ],
        };

        let mut backend = CBackend::new(CBackendConfig::default());
        let c_code = backend.generate_from_ast(&program).unwrap();
        assert!(c_code.contains("x_print"));
        assert!(c_code.contains("Hello, World!"));
        assert!(c_code.contains("int main("));
    }
}
