//! Rust 后端 - 将 X AST 编译为 Rust 代码
//!
//! 生成清晰可读的 Rust 源代码，支持基本的 X 语言特性

use std::fmt::Write;
use std::path::PathBuf;
use x_parser::ast::{self, BinaryOp, ExpressionKind, StatementKind, UnaryOp, Program as AstProgram};

#[derive(Debug, Clone)]
pub struct RustBackendConfig {
    pub output_dir: Option<PathBuf>,
    pub optimize: bool,
    pub debug_info: bool,
}

impl Default for RustBackendConfig {
    fn default() -> Self {
        Self {
            output_dir: None,
            optimize: false,
            debug_info: true,
        }
    }
}

pub struct RustBackend {
    config: RustBackendConfig,
    indent: usize,
    output: String,
}

#[derive(Debug, thiserror::Error)]
pub enum RustBackendError {
    #[error("Generation error: {0}")]
    GenerationError(String),
    #[error("I/O error: {0}")]
    IoError(#[from] std::io::Error),
    #[error("Format error: {0}")]
    FmtError(#[from] std::fmt::Error),
    #[error("Unsupported feature: {0}")]
    UnsupportedFeature(String),
}

pub type RustResult<T> = Result<T, RustBackendError>;

impl RustBackend {
    pub fn new(config: RustBackendConfig) -> Self {
        Self {
            config,
            indent: 0,
            output: String::new(),
        }
    }

    pub fn generate_from_ast(
        &mut self,
        program: &AstProgram,
    ) -> RustResult<super::CodegenOutput> {
        self.output.clear();
        self.indent = 0;

        self.emit_header()?;

        // Emit extern functions
        for decl in &program.declarations {
            if let ast::Declaration::ExternFunction(ext) = decl {
                self.emit_extern_function(ext)?;
            }
        }

        // Emit use statements
        self.emit_uses()?;

        // Emit structs/enums/traits
        for decl in &program.declarations {
            match decl {
                ast::Declaration::Class(class) => self.emit_struct(class)?,
                ast::Declaration::Enum(enum_decl) => self.emit_enum(enum_decl)?,
                ast::Declaration::Trait(trait_decl) => self.emit_trait(trait_decl)?,
                _ => {}
            }
        }

        // Emit global statics/consts
        for decl in &program.declarations {
            if let ast::Declaration::Variable(v) = decl {
                self.emit_global_var(v)?;
            }
        }

        // Emit functions
        let mut has_main = false;
        for decl in &program.declarations {
            if let ast::Declaration::Function(f) = decl {
                self.emit_function(f)?;
                self.line("")?;
                if f.name == "main" {
                    has_main = true;
                }
            }
        }

        // Emit main function only if not already defined
        if !has_main {
            self.emit_main_function()?;
        }

        // Create output file
        let output_file = super::OutputFile {
            path: std::path::PathBuf::from("output.rs"),
            content: self.output.as_bytes().to_vec(),
            file_type: super::FileType::Rust,
        };

        Ok(super::CodegenOutput {
            files: vec![output_file],
            dependencies: vec![],
        })
    }

    fn emit_header(&mut self) -> RustResult<()> {
        self.line("// Generated by X-Lang Rust backend")?;
        self.line("// DO NOT EDIT")?;
        self.line("#![allow(unused)]")?;
        self.line("#![allow(dead_code)]")?;
        self.line("")?;
        Ok(())
    }

    fn emit_uses(&mut self) -> RustResult<()> {
        self.line("use std::collections::HashMap;")?;
        self.line("use std::fmt;")?;
        self.line("")?;
        Ok(())
    }

    fn emit_extern_function(&mut self, ext: &ast::ExternFunctionDecl) -> RustResult<()> {
        let params: Vec<String> = ext
            .parameters
            .iter()
            .map(|p| {
                let ty = if let Some(t) = &p.type_annot {
                    self.emit_type(t)
                } else {
                    "std::ffi::c_void".to_string()
                };
                format!("{}: {}", p.name, ty)
            })
            .collect();

        let return_type = if let Some(rt) = &ext.return_type {
            self.emit_type(rt)
        } else {
            "()".to_string()
        };

        self.line(&format!("#[link(name = \"{}\")]", ext.abi.to_lowercase()))?;
        self.line("extern \"C\" {")?;
        self.indent += 1;
        self.line(&format!(
            "fn {}({}) -> {};",
            ext.name,
            params.join(", "),
            return_type
        ))?;
        self.indent -= 1;
        self.line("}")?;
        self.line("")?;
        Ok(())
    }

    fn emit_struct(&mut self, class: &ast::ClassDecl) -> RustResult<()> {
        let derives = vec!["Debug", "Clone", "PartialEq"];
        self.line(&format!("#[derive({})]", derives.join(", ")))?;

        self.line(&format!("pub struct {} {{", class.name))?;
        self.indent += 1;

        for member in &class.members {
            if let ast::ClassMember::Field(field) = member {
                let ty = if let Some(t) = &field.type_annot {
                    self.emit_type(t)
                } else if let Some(init) = &field.initializer {
                    self.infer_type_from_expr(init)
                } else {
                    "()".to_string()
                };
                let visibility = if field.visibility == ast::Visibility::Public {
                    "pub "
                } else {
                    ""
                };
                self.line(&format!("{}{}: {},", visibility, field.name, ty))?;
            }
        }

        self.indent -= 1;
        self.line("}")?;
        self.line("")?;

        // Emit impl block for methods and constructor
        let has_methods = class
            .members
            .iter()
            .any(|m| matches!(m, ast::ClassMember::Method(_)));
        let has_constructor = class
            .members
            .iter()
            .any(|m| matches!(m, ast::ClassMember::Constructor(_)));

        if has_methods || has_constructor {
            self.line(&format!("impl {} {{", class.name))?;
            self.indent += 1;

            // Emit constructor
            for member in &class.members {
                if let ast::ClassMember::Constructor(constructor) = member {
                    self.emit_constructor(constructor, &class.name)?;
                }
            }

            // Emit methods
            for member in &class.members {
                if let ast::ClassMember::Method(method) = member {
                    self.emit_method(method)?;
                    self.line("")?;
                }
            }

            self.indent -= 1;
            self.line("}")?;
            self.line("")?;
        }

        Ok(())
    }

    fn emit_constructor(&mut self, constructor: &ast::ConstructorDecl, _class_name: &str) -> RustResult<()> {
        let params: Vec<String> = constructor
            .parameters
            .iter()
            .map(|p| {
                let ty = if let Some(t) = &p.type_annot {
                    self.emit_type(t)
                } else {
                    "_".to_string()
                };
                format!("{}: {}", p.name, ty)
            })
            .collect();

        self.line(&format!("pub fn new({}) -> Self {{", params.join(", ")))?;
        self.indent += 1;

        for stmt in &constructor.body.statements {
            self.emit_statement(stmt)?;
        }

        // Default return
        self.line("Self { ..Default::default() }")?;

        self.indent -= 1;
        self.line("}")?;
        self.line("")?;
        Ok(())
    }

    fn emit_method(&mut self, method: &ast::FunctionDecl) -> RustResult<()> {
        let mut params = vec!["&self".to_string()];
        for p in &method.parameters {
            let ty = if let Some(t) = &p.type_annot {
                self.emit_type(t)
            } else {
                "_".to_string()
            };
            params.push(format!("{}: {}", p.name, ty));
        }

        let return_type = if let Some(rt) = &method.return_type {
            format!(" -> {}", self.emit_type(rt))
        } else {
            "".to_string()
        };

        let visibility = if method.modifiers.visibility == ast::Visibility::Public {
            "pub "
        } else {
            ""
        };

        let async_keyword = if method.is_async { "async " } else { "" };

        self.line(&format!(
            "{}{}fn {}({}){} {{",
            visibility,
            async_keyword,
            method.name,
            params.join(", "),
            return_type
        ))?;
        self.indent += 1;

        self.emit_block(&method.body)?;

        if method.return_type.is_some() {
            self.line("Default::default()")?;
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_enum(&mut self, enum_decl: &ast::EnumDecl) -> RustResult<()> {
        self.line("#[derive(Debug, Clone, PartialEq)]")?;
        self.line(&format!("pub enum {} {{", enum_decl.name))?;
        self.indent += 1;

        for variant in &enum_decl.variants {
            match &variant.data {
                ast::EnumVariantData::Unit => {
                    self.line(&format!("{},", variant.name))?;
                }
                ast::EnumVariantData::Tuple(types) => {
                    let type_strs: Vec<String> =
                        types.iter().map(|t| self.emit_type(t)).collect();
                    self.line(&format!("{}({}),", variant.name, type_strs.join(", ")))?;
                }
                ast::EnumVariantData::Record(fields) => {
                    self.line(&format!("{} {{", variant.name))?;
                    self.indent += 1;
                    for (name, ty) in fields {
                        self.line(&format!("{}: {},", name, self.emit_type(ty)))?;
                    }
                    self.indent -= 1;
                    self.line("},")?;
                }
            }
        }

        self.indent -= 1;
        self.line("}")?;
        self.line("")?;
        Ok(())
    }

    fn emit_trait(&mut self, trait_decl: &ast::TraitDecl) -> RustResult<()> {
        self.line(&format!("pub trait {} {{", trait_decl.name))?;
        self.indent += 1;

        for method in &trait_decl.methods {
            let params: Vec<String> = method
                .parameters
                .iter()
                .map(|p| {
                    let ty = if let Some(t) = &p.type_annot {
                        self.emit_type(t)
                    } else {
                        "_".to_string()
                    };
                    format!("{}: {}", p.name, ty)
                })
                .collect();

            let return_type = if let Some(rt) = &method.return_type {
                format!(" -> {}", self.emit_type(rt))
            } else {
                "".to_string()
            };

            self.line(&format!(
                "fn {}({}){};",
                method.name,
                params.join(", "),
                return_type
            ))?;
        }

        self.indent -= 1;
        self.line("}")?;
        self.line("")?;
        Ok(())
    }

    fn emit_global_var(&mut self, v: &ast::VariableDecl) -> RustResult<()> {
        let init = if let Some(expr) = &v.initializer {
            self.emit_expr(expr)?
        } else {
            "Default::default()".to_string()
        };

        let keyword = if v.is_mutable { "static mut" } else { "static" };
        let ty = if let Some(t) = &v.type_annot {
            format!(": {}", self.emit_type(t))
        } else {
            "".to_string()
        };

        if v.is_mutable {
            self.line(&format!("static mut {}{} = {};", v.name, ty, init))?;
        } else {
            self.line(&format!("static {}{} = {};", v.name, ty, init))?;
        }
        Ok(())
    }

    fn emit_function(&mut self, f: &ast::FunctionDecl) -> RustResult<()> {
        let params: Vec<String> = f
            .parameters
            .iter()
            .map(|p| {
                let ty = if let Some(t) = &p.type_annot {
                    self.emit_type(t)
                } else {
                    "_".to_string()
                };
                format!("{}: {}", p.name, ty)
            })
            .collect();

        let return_type = if let Some(rt) = &f.return_type {
            format!(" -> {}", self.emit_type(rt))
        } else {
            "".to_string()
        };

        let visibility = if f.modifiers.visibility == ast::Visibility::Public {
            "pub "
        } else {
            ""
        };

        let async_keyword = if f.is_async { "async " } else { "" };

        self.line(&format!(
            "{}{}fn {}({}){} {{",
            visibility,
            async_keyword,
            f.name,
            params.join(", "),
            return_type
        ))?;
        self.indent += 1;

        self.emit_block(&f.body)?;

        if f.return_type.is_none() {
            self.line("()")?;
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_main_function(&mut self) -> RustResult<()> {
        self.line("fn main() {")?;
        self.indent += 1;
        self.line("println!(\"Hello from Rust backend!\");")?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_block(&mut self, block: &ast::Block) -> RustResult<()> {
        for stmt in &block.statements {
            self.emit_statement(stmt)?;
        }
        Ok(())
    }

    fn emit_statement(&mut self, stmt: &ast::Statement) -> RustResult<()> {
        match &stmt.node {
            StatementKind::Expression(expr) => {
                let e = self.emit_expr(expr)?;
                self.line(&format!("{};", e))?;
            }
            StatementKind::Variable(v) => {
                let init = if let Some(expr) = &v.initializer {
                    self.emit_expr(expr)?
                } else {
                    "Default::default()".to_string()
                };

                let keyword = if v.is_mutable { "let mut" } else { "let" };
                let ty = if let Some(t) = &v.type_annot {
                    format!(": {}", self.emit_type(t))
                } else {
                    "".to_string()
                };

                self.line(&format!("{} {}{} = {};", keyword, v.name, ty, init))?;
            }
            StatementKind::Return(opt) => {
                if let Some(expr) = opt {
                    let e = self.emit_expr(expr)?;
                    self.line(&format!("return {};", e))?;
                } else {
                    self.line("return;")?;
                }
            }
            StatementKind::If(if_stmt) => {
                self.emit_if(if_stmt)?;
            }
            StatementKind::While(while_stmt) => {
                let cond = self.emit_expr(&while_stmt.condition)?;
                self.line(&format!("while {} {{", cond))?;
                self.indent += 1;
                self.emit_block(&while_stmt.body)?;
                self.indent -= 1;
                self.line("}")?;
            }
            StatementKind::For(for_stmt) => {
                self.emit_for(for_stmt)?;
            }
            StatementKind::Match(match_stmt) => {
                self.emit_match(match_stmt)?;
            }
            StatementKind::Try(try_stmt) => {
                self.emit_try(try_stmt)?;
            }
            StatementKind::Break => {
                self.line("break;")?;
            }
            StatementKind::Continue => {
                self.line("continue;")?;
            }
            StatementKind::DoWhile(d) => {
                self.line("loop {")?;
                self.indent += 1;
                self.emit_block(&d.body)?;
                let cond = self.emit_expr(&d.condition)?;
                self.line(&format!("if !({}) {{ break; }}", cond))?;
                self.indent -= 1;
                self.line("}")?;
            }
            StatementKind::Unsafe(block) => {
                self.line("unsafe {")?;
                self.indent += 1;
                self.emit_block(block)?;
                self.indent -= 1;
                self.line("}")?;
            }
        }
        Ok(())
    }

    fn emit_if(&mut self, if_stmt: &ast::IfStatement) -> RustResult<()> {
        let cond = self.emit_expr(&if_stmt.condition)?;
        self.line(&format!("if {} {{", cond))?;
        self.indent += 1;
        self.emit_block(&if_stmt.then_block)?;
        self.indent -= 1;

        if let Some(else_block) = &if_stmt.else_block {
            self.line("} else {")?;
            self.indent += 1;
            self.emit_block(else_block)?;
            self.indent -= 1;
        }
        self.line("}")?;
        Ok(())
    }

    fn emit_for(&mut self, for_stmt: &ast::ForStatement) -> RustResult<()> {
        let iterator = self.emit_expr(&for_stmt.iterator)?;
        let pattern_name = match &for_stmt.pattern {
            ast::Pattern::Variable(name) => name.clone(),
            ast::Pattern::Wildcard => "_".to_string(),
            _ => "item".to_string(),
        };

        self.line(&format!("for {} in {} {{", pattern_name, iterator))?;
        self.indent += 1;
        self.emit_block(&for_stmt.body)?;
        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_match(&mut self, match_stmt: &ast::MatchStatement) -> RustResult<()> {
        let expr = self.emit_expr(&match_stmt.expression)?;
        self.line(&format!("match {} {{", expr))?;
        self.indent += 1;

        for case in &match_stmt.cases {
            let pattern = self.emit_pattern(&case.pattern)?;
            let guard = if let Some(g) = &case.guard {
                format!(" if {}", self.emit_expr(g)?)
            } else {
                "".to_string()
            };
            self.line(&format!("{}{} => {{", pattern, guard))?;
            self.indent += 1;
            self.emit_block(&case.body)?;
            self.indent -= 1;
            self.line("}")?;
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_pattern(&mut self, pattern: &ast::Pattern) -> RustResult<String> {
        match pattern {
            ast::Pattern::Variable(name) => Ok(name.clone()),
            ast::Pattern::Wildcard => Ok("_".to_string()),
            ast::Pattern::Literal(lit) => self.emit_literal_pattern(lit),
            ast::Pattern::Array(patterns) => {
                let pattern_strs: Vec<String> = patterns
                    .iter()
                    .map(|p| self.emit_pattern(p))
                    .collect::<RustResult<Vec<_>>>()?;
                Ok(format!("[{}]", pattern_strs.join(", ")))
            }
            ast::Pattern::Dictionary(entries) => {
                let entries_str: Vec<String> = entries
                    .iter()
                    .map(|(k, v)| {
                        let k_str = self.emit_pattern(k)?;
                        let v_str = self.emit_pattern(v)?;
                        Ok(format!("{}: {}", k_str, v_str))
                    })
                    .collect::<RustResult<Vec<_>>>()?;
                Ok(format!("{{{}}}", entries_str.join(", ")))
            }
            ast::Pattern::Record(name, fields) => {
                let fields_str: Vec<String> = fields
                    .iter()
                    .map(|(n, p)| {
                        let p_str = self.emit_pattern(p)?;
                        Ok(format!("{}: {}", n, p_str))
                    })
                    .collect::<RustResult<Vec<_>>>()?;
                Ok(format!("{} {{ {} }}", name, fields_str.join(", ")))
            }
            ast::Pattern::Tuple(patterns) => {
                let pattern_strs: Vec<String> = patterns
                    .iter()
                    .map(|p| self.emit_pattern(p))
                    .collect::<RustResult<Vec<_>>>()?;
                Ok(format!("({},)", pattern_strs.join(", ")))
            }
            ast::Pattern::Or(left, right) => {
                let left_str = self.emit_pattern(left)?;
                let right_str = self.emit_pattern(right)?;
                Ok(format!("{} | {}", left_str, right_str))
            }
            ast::Pattern::Guard(inner, cond) => {
                let inner_str = self.emit_pattern(inner)?;
                let cond_str = self.emit_expr(cond)?;
                Ok(format!("{} if {}", inner_str, cond_str))
            }
            ast::Pattern::EnumConstructor(type_name, variant_name, patterns) => {
                let pattern_strs: Vec<String> = patterns
                    .iter()
                    .map(|p| self.emit_pattern(p))
                    .collect::<RustResult<Vec<_>>>()?;
                if patterns.is_empty() {
                    Ok(format!("{}::{}", type_name, variant_name))
                } else {
                    Ok(format!("{}::{}({})", type_name, variant_name, pattern_strs.join(", ")))
                }
            }
        }
    }

    fn emit_literal_pattern(&mut self, lit: &ast::Literal) -> RustResult<String> {
        match lit {
            ast::Literal::Integer(n) => Ok(n.to_string()),
            ast::Literal::Float(f) => Ok(f.to_string()),
            ast::Literal::Boolean(b) => Ok(b.to_string()),
            ast::Literal::String(s) => Ok(format!("\"{}\"", s)),
            ast::Literal::Char(c) => Ok(format!("'{}'", c)),
            ast::Literal::Null | ast::Literal::None => Ok("None".to_string()),
            ast::Literal::Unit => Ok("()".to_string()),
        }
    }

    fn emit_try(&mut self, try_stmt: &ast::TryStatement) -> RustResult<()> {
        self.line("{")?;
        self.indent += 1;
        self.line("let __result = (|| {")?;
        self.indent += 1;
        self.emit_block(&try_stmt.body)?;
        self.line("Ok(())")?;
        self.indent -= 1;
        self.line("})();")?;

        self.line("match __result {")?;
        self.indent += 1;

        for cc in &try_stmt.catch_clauses {
            let err_type = cc
                .exception_type
                .as_ref()
                .map(|t| t.clone())
                .unwrap_or_else(|| "_".to_string());
            let var_name = cc
                .variable_name
                .as_ref()
                .map(|n| n.as_str())
                .unwrap_or("_");

            self.line(&format!("Err({}: {}) => {{", var_name, err_type))?;
            self.indent += 1;
            self.emit_block(&cc.body)?;
            self.indent -= 1;
            self.line("}")?;
        }

        self.line("Ok(_) => {}")?;
        self.indent -= 1;
        self.line("}")?;

        if let Some(finally) = &try_stmt.finally_block {
            self.emit_block(finally)?;
        }

        self.indent -= 1;
        self.line("}")?;
        Ok(())
    }

    fn emit_expr(&mut self, expr: &ast::Expression) -> RustResult<String> {
        match &expr.node {
            ExpressionKind::Literal(lit) => self.emit_literal(lit),
            ExpressionKind::Variable(name) => Ok(name.clone()),
            ExpressionKind::Binary(op, left, right) => {
                let left_str = self.emit_expr(left)?;
                let right_str = self.emit_expr(right)?;
                let op_str = self.binary_op_to_rust(op);
                Ok(format!("{} {} {}", left_str, op_str, right_str))
            }
            ExpressionKind::Unary(op, e) => {
                let e_str = self.emit_expr(e)?;
                match op {
                    UnaryOp::Negate => Ok(format!("-{}", e_str)),
                    UnaryOp::Not => Ok(format!("!{}", e_str)),
                    UnaryOp::BitNot => Ok(format!("!{}", e_str)), // Rust uses ! for bitwise not
                    UnaryOp::Wait => Ok(format!("{}.await", e_str)),
                }
            }
            ExpressionKind::Call(callee, args) => {
                let callee_str = self.emit_expr(callee)?;
                let args_str: Vec<String> = args
                    .iter()
                    .map(|a| self.emit_expr(a))
                    .collect::<RustResult<Vec<_>>>()?;
                Ok(format!("{}({})", callee_str, args_str.join(", ")))
            }
            ExpressionKind::Member(obj, name) => {
                let obj_str = self.emit_expr(obj)?;
                Ok(format!("{}.{}", obj_str, name))
            }
            ExpressionKind::Assign(target, value) => {
                let target_str = self.emit_expr(target)?;
                let value_str = self.emit_expr(value)?;
                Ok(format!("{} = {}", target_str, value_str))
            }
            ExpressionKind::If(cond, then, else_) => {
                let cond_str = self.emit_expr(cond)?;
                let then_str = self.emit_expr(then)?;
                let else_str = self.emit_expr(else_)?;
                Ok(format!(
                    "if {} {{ {} }} else {{ {} }}",
                    cond_str, then_str, else_str
                ))
            }
            ExpressionKind::Lambda(params, body) => {
                let params_str: Vec<String> = params
                    .iter()
                    .map(|p| {
                        let ty = if let Some(t) = &p.type_annot {
                            format!(": {}", self.emit_type(t))
                        } else {
                            "".to_string()
                        };
                        format!("{}{}", p.name, ty)
                    })
                    .collect();

                let mut body_output = String::new();
                let saved_output = std::mem::take(&mut self.output);
                self.emit_block(body)?;
                body_output = std::mem::take(&mut self.output);
                self.output = saved_output;

                Ok(format!(
                    "|{}| {{ {} }}",
                    params_str.join(", "),
                    body_output.trim()
                ))
            }
            ExpressionKind::Array(elements) => {
                let elements_str: Vec<String> = elements
                    .iter()
                    .map(|e| self.emit_expr(e))
                    .collect::<RustResult<Vec<_>>>()?;
                Ok(format!("vec![{}]", elements_str.join(", ")))
            }
            ExpressionKind::Dictionary(entries) => {
                if entries.is_empty() {
                    return Ok("HashMap::new()".to_string());
                }
                let entries_str: Vec<String> = entries
                    .iter()
                    .map(|(k, v)| {
                        let k_str = self.emit_expr(k)?;
                        let v_str = self.emit_expr(v)?;
                        Ok(format!("({}, {})", k_str, v_str))
                    })
                    .collect::<RustResult<Vec<_>>>()?;
                Ok(format!(
                    "vec![{}].into_iter().collect()",
                    entries_str.join(", ")
                ))
            }
            ExpressionKind::Range(start, end, inclusive) => {
                let start_str = self.emit_expr(start)?;
                let end_str = self.emit_expr(end)?;
                if *inclusive {
                    Ok(format!("{}..={}", start_str, end_str))
                } else {
                    Ok(format!("{}..{}", start_str, end_str))
                }
            }
            ExpressionKind::Parenthesized(inner) => {
                let inner_str = self.emit_expr(inner)?;
                Ok(format!("({})", inner_str))
            }
            ExpressionKind::Record(name, fields) => {
                let fields_str: Vec<String> = fields
                    .iter()
                    .map(|(n, e)| {
                        let e_str = self.emit_expr(e)?;
                        Ok(format!("{}: {}", n, e_str))
                    })
                    .collect::<RustResult<Vec<_>>>()?;
                Ok(format!("{} {{ {} }}", name, fields_str.join(", ")))
            }
            ExpressionKind::Pipe(input, stages) => {
                let mut result = self.emit_expr(input)?;
                for stage in stages {
                    let stage_str = self.emit_expr(stage)?;
                    result = format!("{}({})", stage_str, result);
                }
                Ok(result)
            }
            ExpressionKind::Wait(wait_type, exprs) => match wait_type {
                ast::WaitType::Single => {
                    if exprs.len() == 1 {
                        let expr_str = self.emit_expr(&exprs[0])?;
                        Ok(format!("{}.await", expr_str))
                    } else {
                        Err(RustBackendError::UnsupportedFeature(
                            "Wait single with multiple expressions".to_string(),
                        ))
                    }
                }
                ast::WaitType::Together => {
                    let exprs_str: Vec<String> = exprs
                        .iter()
                        .map(|e| self.emit_expr(e))
                        .collect::<RustResult<Vec<_>>>()?;
                    Ok(format!("futures::join!({})", exprs_str.join(", ")))
                }
                ast::WaitType::Race => {
                    let exprs_str: Vec<String> = exprs
                        .iter()
                        .enumerate()
                        .map(|(i, e)| {
                            let e_str = self.emit_expr(e)?;
                            Ok(format!("{} => __res{}_{}", e_str, i, i))
                        })
                        .collect::<RustResult<Vec<_>>>()?;
                    Ok(format!("futures::select!({})", exprs_str.join(", ")))
                }
                ast::WaitType::Timeout(_) => {
                    Err(RustBackendError::UnsupportedFeature("Wait with timeout".to_string()))
                }
            },
            ExpressionKind::Needs(name) => Ok(format!("/* needs: {} */", name)),
            ExpressionKind::Given(name, expr) => {
                let expr_str = self.emit_expr(expr)?;
                Ok(format!("/* given {} = {} */", name, expr_str))
            }
            ExpressionKind::Handle(expr, handlers) => {
                let expr_str = self.emit_expr(expr)?;
                let handlers_str: Vec<String> = handlers
                    .iter()
                    .map(|(name, handler)| {
                        let handler_str = self.emit_expr(handler)?;
                        Ok(format!("{} => {}", name, handler_str))
                    })
                    .collect::<RustResult<Vec<_>>>()?;
                Ok(format!(
                    "handle {} with {{ {} }}",
                    expr_str,
                    handlers_str.join(", ")
                ))
            }
            ExpressionKind::TryPropagate(expr) => {
                let expr_str = self.emit_expr(expr)?;
                Ok(format!("{}?", expr_str))
            }
        }
    }

    fn emit_literal(&mut self, lit: &ast::Literal) -> RustResult<String> {
        match lit {
            ast::Literal::Integer(n) => Ok(n.to_string()),
            ast::Literal::Float(f) => Ok(format!("{}f64", f)),
            ast::Literal::Boolean(b) => Ok(b.to_string()),
            ast::Literal::String(s) => Ok(format!("\"{}\".to_string()", s)),
            ast::Literal::Char(c) => Ok(format!("'{}'", c)),
            ast::Literal::Null | ast::Literal::None => Ok("None".to_string()),
            ast::Literal::Unit => Ok("()".to_string()),
        }
    }

    fn binary_op_to_rust(&self, op: &BinaryOp) -> &'static str {
        match op {
            BinaryOp::Add => "+",
            BinaryOp::Sub => "-",
            BinaryOp::Mul => "*",
            BinaryOp::Div => "/",
            BinaryOp::Mod => "%",
            BinaryOp::Pow => ".pow", // Rust doesn't have **, uses method
            BinaryOp::Equal => "==",
            BinaryOp::NotEqual => "!=",
            BinaryOp::Less => "<",
            BinaryOp::LessEqual => "<=",
            BinaryOp::Greater => ">",
            BinaryOp::GreaterEqual => ">=",
            BinaryOp::And => "&&",
            BinaryOp::Or => "||",
            BinaryOp::BitAnd => "&",
            BinaryOp::BitOr => "|",
            BinaryOp::BitXor => "^",
            BinaryOp::LeftShift => "<<",
            BinaryOp::RightShift => ">>",
            BinaryOp::Concat => "+", // String concat
            BinaryOp::RangeExclusive => "..",
            BinaryOp::RangeInclusive => "..=",
        }
    }

    fn emit_type(&self, ty: &ast::Type) -> String {
        match ty {
            ast::Type::Int => "i32".to_string(),
            ast::Type::UnsignedInt => "u32".to_string(),
            ast::Type::Float => "f64".to_string(),
            ast::Type::Bool => "bool".to_string(),
            ast::Type::String => "String".to_string(),
            ast::Type::Char => "char".to_string(),
            ast::Type::Unit => "()".to_string(),
            ast::Type::Never => "!".to_string(),
            ast::Type::Array(inner) => format!("Vec<{}>", self.emit_type(inner)),
            ast::Type::Dictionary(k, v) => {
                format!("HashMap<{}, {}>", self.emit_type(k), self.emit_type(v))
            }
            ast::Type::Option(inner) => format!("Option<{}>", self.emit_type(inner)),
            ast::Type::Result(ok, err) => {
                format!("Result<{}, {}>", self.emit_type(ok), self.emit_type(err))
            }
            ast::Type::Tuple(types) => {
                let type_strs: Vec<String> = types.iter().map(|t| self.emit_type(t)).collect();
                format!("({},)", type_strs.join(", "))
            }
            ast::Type::Function(params, ret) => {
                let params_str: Vec<String> = params.iter().map(|t| self.emit_type(t)).collect();
                format!("fn({}) -> {}", params_str.join(", "), self.emit_type(ret))
            }
            ast::Type::Async(inner) => format!("impl Future<Output = {}>", self.emit_type(inner)),
            ast::Type::Generic(name) | ast::Type::Var(name) => name.clone(),
            ast::Type::TypeParam(name) => name.clone(),
            ast::Type::TypeConstructor(name, args) => {
                let args_str: Vec<String> = args.iter().map(|t| self.emit_type(t)).collect();
                format!("{}<{}>", name, args_str.join(", "))
            }
            ast::Type::Union(name, _) => name.clone(),
            ast::Type::Record(name, _) => name.clone(),
            ast::Type::Dynamic => "Box<dyn std::any::Any>".to_string(),
            // FFI types
            ast::Type::Pointer(inner) => format!("*mut {}", self.emit_type(inner)),
            ast::Type::ConstPointer(inner) => format!("*const {}", self.emit_type(inner)),
            ast::Type::Void => "std::ffi::c_void".to_string(),
            // C FFI types
            ast::Type::CInt => "std::ffi::c_int".to_string(),
            ast::Type::CUInt => "std::ffi::c_uint".to_string(),
            ast::Type::CLong => "std::ffi::c_long".to_string(),
            ast::Type::CULong => "std::ffi::c_ulong".to_string(),
            ast::Type::CLongLong => "std::ffi::c_longlong".to_string(),
            ast::Type::CULongLong => "std::ffi::c_ulonglong".to_string(),
            ast::Type::CFloat => "std::ffi::c_float".to_string(),
            ast::Type::CDouble => "std::ffi::c_double".to_string(),
            ast::Type::CChar => "std::ffi::c_char".to_string(),
            ast::Type::CSize => "usize".to_string(),
            ast::Type::CString => "std::ffi::CString".to_string(),
        }
    }

    fn infer_type_from_expr(&self, expr: &ast::Expression) -> String {
        match &expr.node {
            ExpressionKind::Literal(lit) => match lit {
                ast::Literal::Integer(_) => "i32".to_string(),
                ast::Literal::Float(_) => "f64".to_string(),
                ast::Literal::Boolean(_) => "bool".to_string(),
                ast::Literal::String(_) => "String".to_string(),
                ast::Literal::Char(_) => "char".to_string(),
                ast::Literal::Null | ast::Literal::None => "Option<_>".to_string(),
                ast::Literal::Unit => "()".to_string(),
            },
            ExpressionKind::Array(_) => "Vec<_>".to_string(),
            ExpressionKind::Dictionary(_) => "HashMap<_, _>".to_string(),
            ExpressionKind::Lambda(_, _) => "impl Fn(_)".to_string(),
            ExpressionKind::Record(name, _) => name.clone(),
            ExpressionKind::Variable(name) => name.clone(),
            _ => "_".to_string(),
        }
    }

    fn line(&mut self, s: &str) -> RustResult<()> {
        for _ in 0..self.indent {
            write!(self.output, "    ")?;
        }
        writeln!(self.output, "{}", s)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use x_parser::parser::XParser;

    #[test]
    fn test_empty_program_generation() {
        let source = "";
        let parser = XParser::new();
        let program = parser.parse(source).unwrap();

        let config = RustBackendConfig::default();
        let mut backend = RustBackend::new(config);
        let output = backend.generate_from_ast(&program).unwrap();

        assert_eq!(output.files.len(), 1);
        assert_eq!(output.files[0].path, std::path::PathBuf::from("output.rs"));
    }

    #[test]
    fn test_hello_world_generation() {
        let source = r#"
            function main() {
                print("Hello, World!")
            }
        "#;
        let parser = XParser::new();
        let program = parser.parse(source).unwrap();

        let config = RustBackendConfig::default();
        let mut backend = RustBackend::new(config);
        let output = backend.generate_from_ast(&program).unwrap();

        let content = String::from_utf8(output.files[0].content.clone()).unwrap();
        assert!(content.contains("fn main()"));
    }

    #[test]
    fn test_variable_generation() {
        let source = r#"
            function main() {
                let x = 42
                let mut y = 3.14
            }
        "#;
        let parser = XParser::new();
        let program = parser.parse(source).unwrap();

        let config = RustBackendConfig::default();
        let mut backend = RustBackend::new(config);
        let output = backend.generate_from_ast(&program).unwrap();

        let content = String::from_utf8(output.files[0].content.clone()).unwrap();
        assert!(content.contains("let x = 42"), "Content was: {}", content);
        assert!(content.contains("let mut y = 3.14"), "Content was: {}", content);
    }

    #[test]
    fn test_function_generation() {
        let source = r#"
            function add(a: Int, b: Int) -> Int {
                return a + b
            }
        "#;
        let parser = XParser::new();
        let program = parser.parse(source).unwrap();

        let config = RustBackendConfig::default();
        let mut backend = RustBackend::new(config);
        let output = backend.generate_from_ast(&program).unwrap();

        let content = String::from_utf8(output.files[0].content.clone()).unwrap();
        assert!(content.contains("fn add(a: i32, b: i32) -> i32"));
        assert!(content.contains("return a + b"));
    }

    #[test]
    fn test_extern_function_generation() {
        let source = r#"
            foreign "C" function puts(s: CString) -> CInt
        "#;
        let parser = XParser::new();
        let program = parser.parse(source).unwrap();

        let config = RustBackendConfig::default();
        let mut backend = RustBackend::new(config);
        let output = backend.generate_from_ast(&program).unwrap();

        let content = String::from_utf8(output.files[0].content.clone()).unwrap();
        assert!(content.contains("extern \"C\""));
        assert!(content.contains("fn puts"));
    }

    #[test]
    fn test_unsafe_block_generation() {
        let source = r#"
            function main() {
                unsafe {
                    let x = 42
                }
            }
        "#;
        let parser = XParser::new();
        let program = parser.parse(source).unwrap();

        let config = RustBackendConfig::default();
        let mut backend = RustBackend::new(config);
        let output = backend.generate_from_ast(&program).unwrap();

        let content = String::from_utf8(output.files[0].content.clone()).unwrap();
        assert!(content.contains("unsafe {"));
        assert!(content.contains("let x = 42"));
    }
}
