/* Generated by X-Lang C backend */

#include <stdint.h>
#include <stddef.h>
#include <stdio.h>

typedef enum {
    Option_Some = 0,
    Option_None = 1,

typedef union {
} Option_Union;

typedef struct {
    Option_Union data;
} Option;

typedef enum {
    Result_Ok = 0,

typedef union {
} Result_Union;

typedef struct {
    Result_Union data;
} Result;

extern void println(const char* message);

extern void print(const char* message);

extern void exit(int32_t code);

void panic(const char* message) {
    printf("%d\n", message);
    exit(1);
    return;
}


int main(void) {
    printf("%s\n", "Hello, World!");
    return 0;
}

