/* Generated by X-Lang C backend */
/* DO NOT EDIT */

#include <stdint.h>
#include <stddef.h>
#include <stdio.h>

typedef enum {
    Option_Some = 0,
    Option_None = 1,
} Option_Tag;

typedef union {
    T Some;
} Option_Union;

typedef struct {
    Option_Tag tag;
    Option_Union data;
} Option;

typedef enum {
    Result_Ok = 0,
    Result_Err = 1,
} Result_Tag;

typedef union {
    T Ok;
    E Err;
} Result_Union;

typedef struct {
    Result_Tag tag;
    Result_Union data;
} Result;

extern void println(const char* message);

extern void print(const char* message);

extern void exit(int32_t code);

void panic(const char* message) {
    printf("%d\n", message);
    exit(1);
    return;
}


int main(void) {
    printf("%s\n", "Hello, World!");
    return 0;
}

