/* Generated by X-Lang C backend */
/* DO NOT EDIT */

#include <stdint.h>
#include <stddef.h>
#include <stdio.h>

extern void println(const char* message);

extern void print(const char* message);

extern void exit(int32_t code);

void panic(const char* message) {
    printf("%s\n", message);
    exit(1);
    return;
}

int main(void) {
    printf("%s\n", "Hello, World!");
    return 0;
}
