/* Generated by X-Lang C backend */
/* DO NOT EDIT */

#include <stdint.h>
#include <stddef.h>
#include <stdio.h>

typedef enum {
    Option_Some = 0,
    Option_None = 1,
} Option_Tag;

typedef union {
    T Some;
} Option_Union;

typedef struct {
    Option_Tag tag;
    Option_Union data;
} Option;

typedef enum {
    Result_Ok = 0,
    Result_Err = 1,
} Result_Tag;

typedef union {
    T Ok;
    E Err;
} Result_Union;

typedef struct {
    Result_Tag tag;
    Result_Union data;
} Result;

extern void println(const char* message);

extern void print(const char* message);

extern void exit(int32_t code);

void panic(const char* message) {
    printf("%d\n", message);
    exit(1);
    return;
}

typedef enum {
    Color_Red = 0,
    Color_Green = 1,
    Color_Blue = 2,
} Color;

typedef enum {
    Shape_Circle = 0,
    Shape_Rectangle = 1,
    Shape_Point = 2,
} Shape_Tag;

typedef union {
    f32 Circle;
    struct {
        f32 f0;
        f32 f1;
    } Rectangle;
} Shape_Union;

typedef struct {
    Shape_Tag tag;
    Shape_Union data;
} Shape;

int32_t main(void) {
    const void* c = Color.Red;
    const void* s = Shape.Circle(5);
    printf("%s\n", "Hello from simple enum test!");
    return 0;
}


