// Generated by X-Lang Zig backend
// DO NOT EDIT

const std = @import("std");
fn main() {
    var x : i32 = 42;
    var sqrt_x = std.math.sqrt(f64(x));
    std.debug.print("{}
", .{"Square root of " + std.fmt.allocPrint(std.heap.page_allocator, "{}", .{x}) catch unreachable + " is " + std.fmt.allocPrint(std.heap.page_allocator, "{}", .{sqrt_x}) catch unreachable});
    var s = "Hello, Zig!";
    var len = s.len;
    std.debug.print("{}
", .{"String length: " + std.fmt.allocPrint(std.heap.page_allocator, "{}", .{len}) catch unreachable});
    var allocator = std.heap.page_allocator;
    var buffer = allocator.alloc(u8, 1024) catch unreachable;
    std.debug.print("{}
", .{"Allocated buffer of size: " + std.fmt.allocPrint(std.heap.page_allocator, "{}", .{buffer.len}) catch unreachable});
    allocator.free(buffer);
    std.debug.print("{}
", .{"Zig standard library test completed!"});
    return;
}

