// Generated by X-Lang Zig backend
// DO NOT EDIT

const std = @import("std");

const allocator = std.heap.page_allocator;

pub fn main() void {
    std.debug.print("{s}\n", .{"Starting Flux server on http://127.0.0.1:3000"});
    const _server = @as(i64, 1);
    std.debug.print("{s}\n", .{"Server started, waiting for connections..."});
    while (true) {
        const _conn = @as(i64, 2);
        std.debug.print("{s}\n", .{"Accepted connection"});
        const _data = "";
        std.debug.print("{s}\n", .{"Received request"});
        _ = true;
        _ = conn;
    }
    return;
}

