// Generated by X-Lang Zig backend
// DO NOT EDIT

const std = @import("std");

const allocator = std.heap.page_allocator;

fn xEqual(a: anytype, b: @TypeOf(a)) bool {
    return if (@typeInfo(@TypeOf(a)) == .pointer)
        std.mem.eql(u8, a, b)
    else
        a == b;
}

pub fn main() void {
    std.debug.print("{s}\n", .{"=== E-Commerce API Response Demo ==="});
    std.debug.print("{s}\n", .{""});
    std.debug.print("{s}\n", .{"GET /api/users/1001"});
    _ = blk: { var map = std.StringHashMap([]const u8).init(std.heap.page_allocator); map.put("id", "1001") catch unreachable; map.put("name", "Zhang San") catch unreachable; map.put("email", "zhangsan@example.com") catch unreachable; map.put("role", "admin") catch unreachable; break :blk map; };
    _ = blk: { var map = std.StringHashMap([]const u8).init(std.heap.page_allocator); map.put("id", "1") catch unreachable; map.put("label", "Home") catch unreachable; map.put("street", "88 Tech Road") catch unreachable; map.put("city", "Shenzhen") catch unreachable; break :blk map; };
    std.debug.print("{s}\n", .{"User API response created"});
    std.debug.print("{s}\n", .{""});
    std.debug.print("{s}\n", .{"GET /api/products"});
    _ = blk: { var map = std.StringHashMap(i32).init(std.heap.page_allocator); map.put("id", 101) catch unreachable; map.put("price", 15999) catch unreachable; map.put("stock", 50) catch unreachable; break :blk map; };
    _ = blk: { var map = std.StringHashMap(i32).init(std.heap.page_allocator); map.put("id", 102) catch unreachable; map.put("price", 9999) catch unreachable; map.put("stock", 100) catch unreachable; break :blk map; };
    _ = blk: { var map = std.StringHashMap(i32).init(std.heap.page_allocator); map.put("id", 103) catch unreachable; map.put("price", 1899) catch unreachable; map.put("stock", 200) catch unreachable; break :blk map; };
    std.debug.print("{s}\n", .{"Products API response created"});
    std.debug.print("{s}\n", .{""});
    std.debug.print("{s}\n", .{"GET /api/orders/ORD2024031701"});
    _ = blk: { var map = std.StringHashMap(i32).init(std.heap.page_allocator); map.put("id", 1) catch unreachable; map.put("product_id", 101) catch unreachable; map.put("quantity", 1) catch unreachable; map.put("unit_price", 15999) catch unreachable; break :blk map; };
    _ = blk: { var map = std.StringHashMap(i32).init(std.heap.page_allocator); map.put("id", 2) catch unreachable; map.put("product_id", 103) catch unreachable; map.put("quantity", 2) catch unreachable; map.put("unit_price", 1899) catch unreachable; break :blk map; };
    _ = blk: { var map = std.StringHashMap([]const u8).init(std.heap.page_allocator); map.put("recipient", "Zhang San") catch unreachable; map.put("phone", "13800138000") catch unreachable; map.put("city", "Shanghai") catch unreachable; map.put("country", "China") catch unreachable; break :blk map; };
    _ = blk: { var map = std.StringHashMap([]const u8).init(std.heap.page_allocator); map.put("method", "alipay") catch unreachable; map.put("status", "paid") catch unreachable; break :blk map; };
    std.debug.print("{s}\n", .{"Order API response created"});
    std.debug.print("{s}\n", .{""});
    std.debug.print("{s}\n", .{"GET /api/dashboard/stats"});
    _ = blk: { var map = std.StringHashMap(i32).init(std.heap.page_allocator); map.put("total_users", 15823) catch unreachable; map.put("active_users_today", 3421) catch unreachable; map.put("total_orders", 89234) catch unreachable; map.put("pending_orders", 89) catch unreachable; break :blk map; };
    std.debug.print("{s}\n", .{"Dashboard API response created"});
    std.debug.print("{s}\n", .{""});
    std.debug.print("{s}\n", .{"GET /api/cart"});
    _ = blk: { var map = std.StringHashMap(i32).init(std.heap.page_allocator); map.put("id", 1) catch unreachable; map.put("product_id", 101) catch unreachable; map.put("quantity", 1) catch unreachable; map.put("price", 15999) catch unreachable; break :blk map; };
    _ = blk: { var map = std.StringHashMap(i32).init(std.heap.page_allocator); map.put("total_items", 1) catch unreachable; map.put("subtotal", 15999) catch unreachable; map.put("total", 15999) catch unreachable; break :blk map; };
    std.debug.print("{s}\n", .{"Cart API response created"});
    std.debug.print("{s}\n", .{""});
    std.debug.print("{s}\n", .{"=== API Demo Complete ==="});
}

