"use strict";
// Generated by X-Lang TypeScript 6.0 backend
// DO NOT EDIT
// Target: TypeScript 6.0 / ES2025 (March 2026)
// tsconfig: strict=true, module=esnext
function main() {
    let t0;
    bb0: t0 = (console.log("Hello, World!"), 0);
    return 0;
}
// Entry point
main();
