// Generated by X-Lang TypeScript 6.0 backend
// DO NOT EDIT
// Target: TypeScript 6.0 / ES2025 (March 2026)
// tsconfig: strict=true, module=esnext

declare function printf(arg0: string): number;

declare function malloc(arg0: number): unknown;

declare function free(arg0: unknown): void;

declare function x_perceus_retain(arg0: unknown): void;

declare function x_perceus_release(arg0: unknown): void;

function main(): number {
    let t0: number;
    bb0:
    t0 = (console.log("Hello, World!"), 0);
    return 0;
}

// Entry point
main();
